import { ElementType, ForwardedRef, ReactElement, ReactNode, forwardRef } from "react";
import { omitProps } from "../../shared";

export interface StrictBoxProps {
    /**
    * An HTML element type or a custom React element type to render as.
    */
    as?: ElementType;
    /**
     * [Slot](?path=/docs/getting-started-slots--page) to render into.
     */
    slot?: string
    /*
     * React children
    */
    children?: ReactNode;
    /**
     * @ignore
     */
    forwardedRef: ForwardedRef<any>
}

export interface BoxProps extends StrictBoxProps {
    /**
     * This property is used to allow extra properties to be passed down to the component generated by the "as" property
     */
    [key: string]: any;
}

export function InnerBox(props: BoxProps): ReactElement {
    const {
        as: Wrapper = "div",
        children,
        forwardedRef,
        ...rest
    } = omitProps(props, ["slot"]);

    return (
        <Wrapper
            {...rest}
            ref={forwardedRef}
        >
            {children}
        </Wrapper>
    );
}

export const Box = forwardRef<any, BoxProps>((props, ref) => (
    <InnerBox {...props} forwardedRef={ref} />
));

Box.displayName = "Box";

