import { ElementType, ForwardedRef, PropsWithChildren, RefAttributes, forwardRef } from "react";
import { omitProps } from "../../shared";



export interface AsProps<As extends ElementType = ElementType> {
    /**
    * An HTML element type or a custom React element type to render as.
    */
    as?: As;
}

export type AsPropsWithChildren<As extends ElementType = ElementType> = PropsWithChildren<AsProps<As>>;

export interface SlottableElement {
    /**
     * [Slot](?path=/docs/getting-started-slots--page) to render into.
     */
    slot?: string

}

interface StrictBoxProps extends AsPropsWithChildren, SlottableElement, RefAttributes<unknown> {
    /**
     * @ignore
     */
    // ref: ForwardedRef<unknown>
}

interface BoxProps extends StrictBoxProps {
    /**
     * This property is used to allow extra properties to be passed down to the component generated by the "as" property
     */
    [key: string]: any;
}


export function InnerBox(props: BoxProps) {
    const {
        as: Wrapper = "div",
        children,
        ref,
        ...rest
    } = omitProps(props, ["slot"]);

    return (
        <Wrapper
            {...rest}
            ref={ref}
        >
            {children}
        </Wrapper>
    );
}

export const Box = forwardRef((props, ref) => (
    <InnerBox {...props} ref={ref} />
));

Box.displayName = "Box";


