import { Icon, MultiVariantIcon } from "./icon";

function createOrbitIcon(source) {
    return props => {
        return <Icon source={source} {...props} />;
    };
}

function createOrbitMultiVariantIcon(source24, source32) {
    return props => {
        return <MultiVariantIcon source24={source24} source32={source32} {...props} />;
    };
}

import { ReactComponent as PureAddIcon24 } from "./icon-add-24.svg";
import { ReactComponent as PureAddIcon32 } from "./icon-add-32.svg";
import { ReactComponent as PureAddUserIcon32 } from "./icon-add-user-32.svg";
import { ReactComponent as PureArrowIcon24 } from "./icon-arrow-24.svg";
import { ReactComponent as PureArrowIcon32 } from "./icon-arrow-32.svg";
import { ReactComponent as PureCalendarIcon24 } from "./icon-calendar-24.svg";
import { ReactComponent as PureCalendarIcon32 } from "./icon-calendar-32.svg";
import { ReactComponent as PureCheckIcon24 } from "./icon-check-24.svg";
import { ReactComponent as PureCheckIcon32 } from "./icon-check-32.svg";
import { ReactComponent as PureCircleIcon24 } from "./icon-circle-24.svg";
import { ReactComponent as PureCircleIcon32 } from "./icon-circle-32.svg";
import { ReactComponent as PureClearFilterIcon24 } from "./icon-clear-filter-24.svg";
import { ReactComponent as PureClearFilterIcon32 } from "./icon-clear-filter-32.svg";
import { ReactComponent as PureCloseIcon24 } from "./icon-close-24.svg";
import { ReactComponent as PureCloseIcon32 } from "./icon-close-32.svg";
import { ReactComponent as PureCommunicationIcon32 } from "./icon-communication-32.svg";
import { ReactComponent as PureCompareIcon24 } from "./icon-compare-24.svg";
import { ReactComponent as PureCompareIcon32 } from "./icon-compare-32.svg";
import { ReactComponent as PureCsvIcon32 } from "./icon-csv-32.svg";
import { ReactComponent as PureDoNotDisturbIcon32 } from "./icon-do-not-disturb-32.svg";
import { ReactComponent as PureDownloadIcon32 } from "./icon-download-32.svg";
import { ReactComponent as PureEditIcon32 } from "./icon-edit-32.svg";
import { ReactComponent as PureFileIcon32 } from "./icon-file-32.svg";
import { ReactComponent as PureFolderIcon32 } from "./icon-folder-32.svg";
import { ReactComponent as PureGarbageIcon32 } from "./icon-garbage-32.svg";
import { ReactComponent as PureGearIcon32 } from "./icon-gear-32.svg";
import { ReactComponent as PureGroupIcon32 } from "./icon-group-32.svg";
import { ReactComponent as PureHelpIcon24 } from "./icon-help-24.svg";
import { ReactComponent as PureHelpIcon32 } from "./icon-help-32.svg";
import { ReactComponent as PureHorizontalDotsIcon32 } from "./icon-horizontal-dots-32.svg";
import { ReactComponent as PureImageIcon32 } from "./icon-image-32.svg";
import { ReactComponent as PureInfoIcon24 } from "./icon-info-24.svg";
import { ReactComponent as PureInfoIcon32 } from "./icon-info-32.svg";
import { ReactComponent as PureLightbulbIcon24 } from "./icon-lightbulb-24.svg";
import { ReactComponent as PureLightbulbIcon32 } from "./icon-lightbulb-32.svg";
import { ReactComponent as PureMagnifierIcon32 } from "./icon-magnifier-32.svg";
import { ReactComponent as PureMusicIcon32 } from "./icon-music-32.svg";
import { ReactComponent as PureNotificationIcon24 } from "./icon-notification-24.svg";
import { ReactComponent as PureNotificationIcon32 } from "./icon-notification-32.svg";
import { ReactComponent as PurePdfIcon32 } from "./icon-pdf-32.svg";
import { ReactComponent as PurePrinterIcon24 } from "./icon-printer-24.svg";
import { ReactComponent as PurePrinterIcon32 } from "./icon-printer-32.svg";
import { ReactComponent as PurePrivacyIcon24 } from "./icon-privacy-24.svg";
import { ReactComponent as PureReminderIcon32 } from "./icon-reminder-32.svg";
import { ReactComponent as PureRemoveUserIcon32 } from "./icon-remove-user-32.svg";
import { ReactComponent as PureSignoutIcon24 } from "./icon-signout-24.svg";
import { ReactComponent as PureSignoutIcon32 } from "./icon-signout-32.svg";
import { ReactComponent as PureSortingIcon24 } from "./icon-sorting-24.svg";
import { ReactComponent as PureSortingIcon32 } from "./icon-sorting-32.svg";
import { ReactComponent as PureVariationIcon24 } from "./icon-variation-24.svg";
import { ReactComponent as PureVariationIcon32 } from "./icon-variation-32.svg";
import { ReactComponent as PureVerticalDotsIcon32 } from "./icon-vertical-dots-32.svg";
import { ReactComponent as PureVideoIcon32 } from "./icon-video-32.svg";
import { ReactComponent as PureWarningIcon24 } from "./icon-warning-24.svg";
import { ReactComponent as PureWarningIcon32 } from "./icon-warning-32.svg";
import { ReactComponent as PureZipIcon32 } from "./icon-zip-32.svg";

export const AddIcon24 = createOrbitIcon(<PureAddIcon24 />);
export const AddIcon32 = createOrbitIcon(<PureAddIcon32 />);
export const AddUserIcon32 = createOrbitIcon(<PureAddUserIcon32 />);
export const ArrowIcon24 = createOrbitIcon(<PureArrowIcon24 />);
export const ArrowIcon32 = createOrbitIcon(<PureArrowIcon32 />);
export const CalendarIcon24 = createOrbitIcon(<ureCalendarIcon24 />);
export const CalendarIcon32 = createOrbitIcon(<PureCalendarIcon32 />);
export const CheckIcon24 = createOrbitIcon(<PureCheckIcon24 />);
export const CheckIcon32 = createOrbitIcon(<PureCheckIcon32 />);
export const CircleIcon24 = createOrbitIcon(<PureCircleIcon24 />);
export const CircleIcon32 = createOrbitIcon(<PureCircleIcon32 />);
export const ClearFilterIcon24 = createOrbitIcon(<PureClearFilterIcon24 />);
export const ClearFilterIcon32 = createOrbitIcon(<PureClearFilterIcon32 />);
export const CloseIcon24 = createOrbitIcon(<PureCloseIcon24 />);
export const CloseIcon32 = createOrbitIcon(<PureCloseIcon32 />);
export const CommunicationIcon32 = createOrbitIcon(<PureCommunicationIcon32 />);
export const CompareIcon24 = createOrbitIcon(<PureCompareIcon24 />);
export const CompareIcon32 = createOrbitIcon(<PureCompareIcon32 />);
export const CsvIcon32 = createOrbitIcon(<PureCsvIcon32 />);
export const DoNotDisturbIcon32 = createOrbitIcon(<PureDoNotDisturbIcon32 />);
export const DownloadIcon32 = createOrbitIcon(<PureDownloadIcon32 />);
export const EditIcon32 = createOrbitIcon(<PureEditIcon32 />);
export const FileIcon32 = createOrbitIcon(<PureFileIcon32 />);
export const FolderIcon32 = createOrbitIcon(<PureFolderIcon32 />);
export const GarbageIcon32 = createOrbitIcon(<PureGarbageIcon32 />);
export const GearIcon32 = createOrbitIcon(<PureGearIcon32 />);
export const GroupIcon32 = createOrbitIcon(<PureGroupIcon32 />);
export const HelpIcon24 = createOrbitIcon(<PureHelpIcon24 />);
export const HelpIcon32 = createOrbitIcon(<PureHelpIcon32 />);
export const HorizontalDotsIcon32 = createOrbitIcon(<PureHorizontalDotsIcon32 />);
export const ImageIcon32 = createOrbitIcon(<PureImageIcon32 />);
export const InfoIcon24 = createOrbitIcon(<PureInfoIcon24 />);
export const InfoIcon32 = createOrbitIcon(<PureInfoIcon32 />);
export const LightbulbIcon24 = createOrbitIcon(<PureLightbulbIcon24 />);
export const LightbulbIcon32 = createOrbitIcon(<PureLightbulbIcon32 />);
export const MagnifierIcon32 = createOrbitIcon(<PureMagnifierIcon32 />);
export const MusicIcon32 = createOrbitIcon(<PureMusicIcon32 />);
export const NotificationIcon24 = createOrbitIcon(<PureNotificationIcon24 />);
export const NotificationIcon32 = createOrbitIcon(<PureNotificationIcon32 />);
export const PdfIcon32 = createOrbitIcon(<PurePdfIcon32 />);
export const PrinterIcon24 = createOrbitIcon(<PurePrinterIcon24 />);
export const PrinterIcon32 = createOrbitIcon(<PurePrinterIcon32 />);
export const PrivacyIcon24 = createOrbitIcon(<PurePrivacyIcon24 />);
export const ReminderIcon32 = createOrbitIcon(<PureReminderIcon32 />);
export const RemoveUserIcon32 = createOrbitIcon(<PureRemoveUserIcon32 />);
export const SignoutIcon24 = createOrbitIcon(<PureSignoutIcon24 />);
export const SignoutIcon32 = createOrbitIcon(<PureSignoutIcon32 />);
export const SortingIcon24 = createOrbitIcon(<PureSortingIcon24 />);
export const SortingIcon32 = createOrbitIcon(<PureSortingIcon32 />);
export const VariationIcon24 = createOrbitIcon(<PureVariationIcon24 />);
export const VariationIcon32 = createOrbitIcon(<PureVariationIcon32 />);
export const VerticalDotsIcon32 = createOrbitIcon(<PureVerticalDotsIcon32 />);
export const VideoIcon32 = createOrbitIcon(<PureVideoIcon32 />);
export const WarningIcon24 = createOrbitIcon(<PureWarningIcon24 />);
export const WarningIcon32 = createOrbitIcon(<PureWarningIcon32 />);
export const ZipIcon32 = createOrbitIcon(<PureZipIcon32 />);

export const AddIcon = createOrbitMultiVariantIcon(<PureAddIcon24 />, <PureAddIcon32 />);
export const AddUserIcon = createOrbitMultiVariantIcon(<PureAddUserIcon32 />, <PureAddUserIcon32 />);
export const ArrowIcon = createOrbitMultiVariantIcon(<PureArrowIcon24 />, <PureArrowIcon32 />);
export const CalendarIcon = createOrbitMultiVariantIcon(<PureCalendarIcon24 />, <PureCalendarIcon32 />);
export const CheckIcon = createOrbitMultiVariantIcon(<PureCheckIcon24 />, <PureCheckIcon32 />);
export const CircleIcon = createOrbitMultiVariantIcon(<PureCircleIcon24 />, <PureCircleIcon32 />);
export const ClearFilterIcon = createOrbitMultiVariantIcon(<PureClearFilterIcon24 />, <PureClearFilterIcon32 />);
export const CloseIcon = createOrbitMultiVariantIcon(<PureCloseIcon24 />, <PureCloseIcon32 />);
export const CommunicationIcon = createOrbitMultiVariantIcon(<PureCommunicationIcon32 />, <PureCommunicationIcon32 />);
export const CompareIcon = createOrbitMultiVariantIcon(<PureCompareIcon24 />, <PureCompareIcon32 />);
export const CsvIcon = createOrbitMultiVariantIcon(<PureCsvIcon32 />, <PureCsvIcon32 />);
export const DoNotDisturbIcon = createOrbitMultiVariantIcon(<PureDoNotDisturbIcon32 />, <PureDoNotDisturbIcon32 />);
export const DownloadIcon = createOrbitMultiVariantIcon(<PureDownloadIcon32 />, <PureDownloadIcon32 />);
export const EditIcon = createOrbitMultiVariantIcon(<PureEditIcon32 />, <PureEditIcon32 />);
export const FileIcon = createOrbitMultiVariantIcon(<PureFileIcon32 />, <PureFileIcon32 />);
export const FolderIcon = createOrbitMultiVariantIcon(<PureFolderIcon32 />, <PureFolderIcon32 />);
export const GarbageIcon = createOrbitMultiVariantIcon(<PureGarbageIcon32 />, <PureGarbageIcon32 />);
export const GearIcon = createOrbitMultiVariantIcon(<PureGearIcon32 />, <PureGearIcon32 />);
export const GroupIcon = createOrbitMultiVariantIcon(<PureGroupIcon32 />, <PureGroupIcon32 />);
export const HelpIcon = createOrbitMultiVariantIcon(<PureHelpIcon24 />, <PureHelpIcon32 />);
export const HorizontalDotsIcon = createOrbitMultiVariantIcon(<PureHorizontalDotsIcon32 />, <PureHorizontalDotsIcon32 />);
export const ImageIcon = createOrbitMultiVariantIcon(<PureImageIcon32 />, <PureImageIcon32 />);
export const InfoIcon = createOrbitMultiVariantIcon(<PureInfoIcon24 />, <PureInfoIcon32 />);
export const LightbulbIcon = createOrbitMultiVariantIcon(<PureLightbulbIcon24 />, <PureLightbulbIcon32 />);
export const MagnifierIcon = createOrbitMultiVariantIcon(<PureMagnifierIcon32 />, <PureMagnifierIcon32 />);
export const MusicIcon = createOrbitMultiVariantIcon(<PureMusicIcon32 />, <PureMusicIcon32 />);
export const NotificationIcon = createOrbitMultiVariantIcon(<PureNotificationIcon24 />, <PureNotificationIcon32 />);
export const PdfIcon = createOrbitMultiVariantIcon(<PurePdfIcon32 />, <PurePdfIcon32 />);
export const PrinterIcon = createOrbitMultiVariantIcon(<PurePrinterIcon24 />, <PurePrinterIcon32 />);
export const PrivacyIcon = createOrbitMultiVariantIcon(<PurePrivacyIcon24 />, <PurePrivacyIcon24 />);
export const ReminderIcon = createOrbitMultiVariantIcon(<PureReminderIcon32 />, <PureReminderIcon32 />);
export const RemoveUserIcon = createOrbitMultiVariantIcon(<PureRemoveUserIcon32 />, <PureRemoveUserIcon32 />);
export const SignoutIcon = createOrbitMultiVariantIcon(<PureSignoutIcon24 />, <PureSignoutIcon32 />);
export const SortingIcon = createOrbitMultiVariantIcon(<PureSortingIcon24 />, <PureSortingIcon32 />);
export const VariationIcon = createOrbitMultiVariantIcon(<PureVariationIcon24 />, <PureVariationIcon32 />);
export const VerticalDotsIcon = createOrbitMultiVariantIcon(<PureVerticalDotsIcon32 />, <PureVerticalDotsIcon32 />);
export const VideoIcon = createOrbitMultiVariantIcon(<PureVideoIcon32 />, <PureVideoIcon32 />);
export const WarningIcon = createOrbitMultiVariantIcon(<PureWarningIcon24 />, <PureWarningIcon32 />);
export const ZipIcon = createOrbitMultiVariantIcon(<PureZipIcon32 />, <PureZipIcon32 />);

export * from "./factories";
export * from "./sizes";
export * from "./icon";
