/*
Behaviors
-

disabled
couple of tests that are already done with popup

Aria
- when an id is provided for the tooltip, it is used as the tooltip id
- when no tooltip id is provided, a tooltip id is autogenerated
- when a tooltip is visible, the tooltip trigger aria-describedby match the tooltip id

Api
- call onOpenChange when the tooltip appears
- call onOpenChange when the tooltip disappear

Refs
*/
