/*

ADD TO CHECKBOXGROUP & RADIOGROUP: value autogenerated

Behaviors
- when autofocus is true, the first tile is focused on render

Aria
- when selectionMode is \"single\" the group role is \"radiogroup\"
- when selectionMode is \"single\", the tile role is \"radio\"
- when selectionMode is \"multiple\", the group role is \"group\"
- when selectionMode is \"multiple\", the tile role is \"checkbox\"

Api
- when selectionMode is \"single\", call onChange when a tile is selected
- when selectionMode is \"single\", call onChange when then selected tile change
- when selectionMode is \"multiple\", call onChange when a tile is selected
- when selectionMode is \"multiple\" and multiple tiles are selected, call onChange when a tile is selected
- when selectionMode is \"multiple\", call onChange when a tile is unselected
- when selectionMode is \"single\" call the tile onChange handler when a tile is selected
- when selectionMode is \"multiple\", call the tile onChange handler when a tile is selected

Refs
- classic refs
*/
