import { Icon, MultiVariantIcon } from "./Icon";

export * from "./Icon";
export * from "./EmbeddedIcon";

function createOrbitIcon(source) {
    return Icon.create(source);
}

function createOrbitMultiVariantIcon(source24, source32) {
    return MultiVariantIcon.create(source24, source32);
}

import { ReactComponent as InnerAddGuestIcon24 } from "@orbit-ui/icons/dist/icon-add-guest-24.svg";
import { ReactComponent as InnerAddGuestIcon32 } from "@orbit-ui/icons/dist/icon-add-guest-32.svg";
import { ReactComponent as InnerAddIcon24 } from "@orbit-ui/icons/dist/icon-add-24.svg";
import { ReactComponent as InnerAddIcon32 } from "@orbit-ui/icons/dist/icon-add-32.svg";
import { ReactComponent as InnerAddUserIcon24 } from "@orbit-ui/icons/dist/icon-add-user-24.svg";
import { ReactComponent as InnerAddUserIcon32 } from "@orbit-ui/icons/dist/icon-add-user-32.svg";
import { ReactComponent as InnerArrowIcon24 } from "@orbit-ui/icons/dist/icon-arrow-24.svg";
import { ReactComponent as InnerArrowIcon32 } from "@orbit-ui/icons/dist/icon-arrow-32.svg";
import { ReactComponent as InnerBellIcon24 } from "@orbit-ui/icons/dist/icon-bell-24.svg";
import { ReactComponent as InnerBellIcon32 } from "@orbit-ui/icons/dist/icon-bell-32.svg";
import { ReactComponent as InnerCalendarIcon24 } from "@orbit-ui/icons/dist/icon-calendar-24.svg";
import { ReactComponent as InnerCalendarIcon32 } from "@orbit-ui/icons/dist/icon-calendar-32.svg";
import { ReactComponent as InnerCarretIcon24 } from "@orbit-ui/icons/dist/icon-carret-24.svg";
import { ReactComponent as InnerCarretIcon32 } from "@orbit-ui/icons/dist/icon-carret-32.svg";
import { ReactComponent as InnerCheckIcon24 } from "@orbit-ui/icons/dist/icon-check-24.svg";
import { ReactComponent as InnerCheckIcon32 } from "@orbit-ui/icons/dist/icon-check-32.svg";
import { ReactComponent as InnerCheckCircleIcon24 } from "@orbit-ui/icons/dist/icon-check-circle-24.svg";
import { ReactComponent as InnerCheckCircleIcon32 } from "@orbit-ui/icons/dist/icon-check-circle-32.svg";
import { ReactComponent as InnerChevronIcon24 } from "@orbit-ui/icons/dist/icon-chevron-24.svg";
import { ReactComponent as InnerChevronIcon32 } from "@orbit-ui/icons/dist/icon-chevron-32.svg";
import { ReactComponent as InnerCircleIcon24 } from "@orbit-ui/icons/dist/icon-circle-24.svg";
import { ReactComponent as InnerCircleIcon32 } from "@orbit-ui/icons/dist/icon-circle-32.svg";
import { ReactComponent as InnerClearFilterIcon24 } from "@orbit-ui/icons/dist/icon-clear-filter-24.svg";
import { ReactComponent as InnerClearFilterIcon32 } from "@orbit-ui/icons/dist/icon-clear-filter-32.svg";
import { ReactComponent as InnerCloseIcon24 } from "@orbit-ui/icons/dist/icon-close-24.svg";
import { ReactComponent as InnerCloseIcon32 } from "@orbit-ui/icons/dist/icon-close-32.svg";
import { ReactComponent as InnerCommunicationIcon24 } from "@orbit-ui/icons/dist/icon-communication-24.svg";
import { ReactComponent as InnerCommunicationIcon32 } from "@orbit-ui/icons/dist/icon-communication-32.svg";
import { ReactComponent as InnerCsvIcon24 } from "@orbit-ui/icons/dist/icon-csv-24.svg";
import { ReactComponent as InnerCsvIcon32 } from "@orbit-ui/icons/dist/icon-csv-32.svg";
import { ReactComponent as InnerDashIcon24 } from "@orbit-ui/icons/dist/icon-dash-24.svg";
import { ReactComponent as InnerDashIcon32 } from "@orbit-ui/icons/dist/icon-dash-32.svg";
import { ReactComponent as InnerDoNotDisturbIcon24 } from "@orbit-ui/icons/dist/icon-do-not-disturb-24.svg";
import { ReactComponent as InnerDoNotDisturbIcon32 } from "@orbit-ui/icons/dist/icon-do-not-disturb-32.svg";
import { ReactComponent as InnerDownloadIcon24 } from "@orbit-ui/icons/dist/icon-download-24.svg";
import { ReactComponent as InnerDownloadIcon32 } from "@orbit-ui/icons/dist/icon-download-32.svg";
import { ReactComponent as InnerEditIcon24 } from "@orbit-ui/icons/dist/icon-edit-24.svg";
import { ReactComponent as InnerEditIcon32 } from "@orbit-ui/icons/dist/icon-edit-32.svg";
import { ReactComponent as InnerFileIcon24 } from "@orbit-ui/icons/dist/icon-file-24.svg";
import { ReactComponent as InnerFileIcon32 } from "@orbit-ui/icons/dist/icon-file-32.svg";
import { ReactComponent as InnerFilterIcon24 } from "@orbit-ui/icons/dist/icon-filter-24.svg";
import { ReactComponent as InnerFilterIcon32 } from "@orbit-ui/icons/dist/icon-filter-32.svg";
import { ReactComponent as InnerFlagIcon24 } from "@orbit-ui/icons/dist/icon-flag-24.svg";
import { ReactComponent as InnerFlagIcon32 } from "@orbit-ui/icons/dist/icon-flag-32.svg";
import { ReactComponent as InnerFolderIcon24 } from "@orbit-ui/icons/dist/icon-folder-24.svg";
import { ReactComponent as InnerFolderIcon32 } from "@orbit-ui/icons/dist/icon-folder-32.svg";
import { ReactComponent as InnerGearIcon24 } from "@orbit-ui/icons/dist/icon-gear-24.svg";
import { ReactComponent as InnerGearIcon32 } from "@orbit-ui/icons/dist/icon-gear-32.svg";
import { ReactComponent as InnerGroupIcon24 } from "@orbit-ui/icons/dist/icon-group-24.svg";
import { ReactComponent as InnerGroupIcon32 } from "@orbit-ui/icons/dist/icon-group-32.svg";
import { ReactComponent as InnerHelpIcon24 } from "@orbit-ui/icons/dist/icon-help-24.svg";
import { ReactComponent as InnerHelpIcon32 } from "@orbit-ui/icons/dist/icon-help-32.svg";
import { ReactComponent as InnerHorizontalDotsIcon24 } from "@orbit-ui/icons/dist/icon-horizontal-dots-24.svg";
import { ReactComponent as InnerHorizontalDotsIcon32 } from "@orbit-ui/icons/dist/icon-horizontal-dots-32.svg";
import { ReactComponent as InnerInfoIcon24 } from "@orbit-ui/icons/dist/icon-info-24.svg";
import { ReactComponent as InnerInfoIcon32 } from "@orbit-ui/icons/dist/icon-info-32.svg";
import { ReactComponent as InnerLightbulbIcon24 } from "@orbit-ui/icons/dist/icon-lightbulb-24.svg";
import { ReactComponent as InnerLightbulbIcon32 } from "@orbit-ui/icons/dist/icon-lightbulb-32.svg";
import { ReactComponent as InnerMagnifierIcon24 } from "@orbit-ui/icons/dist/icon-magnifier-24.svg";
import { ReactComponent as InnerMagnifierIcon32 } from "@orbit-ui/icons/dist/icon-magnifier-32.svg";
import { ReactComponent as InnerMusicIcon24 } from "@orbit-ui/icons/dist/icon-music-24.svg";
import { ReactComponent as InnerMusicIcon32 } from "@orbit-ui/icons/dist/icon-music-32.svg";
import { ReactComponent as InnerPdfIcon24 } from "@orbit-ui/icons/dist/icon-pdf-24.svg";
import { ReactComponent as InnerPdfIcon32 } from "@orbit-ui/icons/dist/icon-pdf-32.svg";
import { ReactComponent as InnerPictureIcon24 } from "@orbit-ui/icons/dist/icon-picture-24.svg";
import { ReactComponent as InnerPictureIcon32 } from "@orbit-ui/icons/dist/icon-picture-32.svg";
import { ReactComponent as InnerPrinterIcon24 } from "@orbit-ui/icons/dist/icon-printer-24.svg";
import { ReactComponent as InnerPrinterIcon32 } from "@orbit-ui/icons/dist/icon-printer-32.svg";
import { ReactComponent as InnerPrivacyIcon24 } from "@orbit-ui/icons/dist/icon-privacy-24.svg";
import { ReactComponent as InnerReminderIcon24 } from "@orbit-ui/icons/dist/icon-reminder-24.svg";
import { ReactComponent as InnerReminderIcon32 } from "@orbit-ui/icons/dist/icon-reminder-32.svg";
import { ReactComponent as InnerRemoveGuestIcon24 } from "@orbit-ui/icons/dist/icon-remove-guest-24.svg";
import { ReactComponent as InnerRemoveGuestIcon32 } from "@orbit-ui/icons/dist/icon-remove-guest-32.svg";
import { ReactComponent as InnerRemoveUserIcon24 } from "@orbit-ui/icons/dist/icon-remove-user-24.svg";
import { ReactComponent as InnerRemoveUserIcon32 } from "@orbit-ui/icons/dist/icon-remove-user-32.svg";
import { ReactComponent as InnerSignoutIcon24 } from "@orbit-ui/icons/dist/icon-signout-24.svg";
import { ReactComponent as InnerSignoutIcon32 } from "@orbit-ui/icons/dist/icon-signout-32.svg";
import { ReactComponent as InnerSlashIcon24 } from "@orbit-ui/icons/dist/icon-slash-24.svg";
import { ReactComponent as InnerSlashIcon32 } from "@orbit-ui/icons/dist/icon-slash-32.svg";
import { ReactComponent as InnerSortIcon24 } from "@orbit-ui/icons/dist/icon-sort-24.svg";
import { ReactComponent as InnerSortIcon32 } from "@orbit-ui/icons/dist/icon-sort-32.svg";
import { ReactComponent as InnerTrashIcon24 } from "@orbit-ui/icons/dist/icon-trash-24.svg";
import { ReactComponent as InnerTrashIcon32 } from "@orbit-ui/icons/dist/icon-trash-32.svg";
import { ReactComponent as InnerUpDownIcon24 } from "@orbit-ui/icons/dist/icon-up-down-24.svg";
import { ReactComponent as InnerUpDownIcon32 } from "@orbit-ui/icons/dist/icon-up-down-32.svg";
import { ReactComponent as InnerVerticalDotsIcon24 } from "@orbit-ui/icons/dist/icon-vertical-dots-24.svg";
import { ReactComponent as InnerVerticalDotsIcon32 } from "@orbit-ui/icons/dist/icon-vertical-dots-32.svg";
import { ReactComponent as InnerVideoIcon24 } from "@orbit-ui/icons/dist/icon-video-24.svg";
import { ReactComponent as InnerVideoIcon32 } from "@orbit-ui/icons/dist/icon-video-32.svg";
import { ReactComponent as InnerWarningIcon24 } from "@orbit-ui/icons/dist/icon-warning-24.svg";
import { ReactComponent as InnerWarningIcon32 } from "@orbit-ui/icons/dist/icon-warning-32.svg";
import { ReactComponent as InnerZipIcon24 } from "@orbit-ui/icons/dist/icon-zip-24.svg";
import { ReactComponent as InnerZipIcon32 } from "@orbit-ui/icons/dist/icon-zip-32.svg";

export const AddGuestIcon24 = createOrbitIcon(InnerAddGuestIcon24);
export const AddGuestIcon32 = createOrbitIcon(InnerAddGuestIcon32);
export const AddIcon24 = createOrbitIcon(InnerAddIcon24);
export const AddIcon32 = createOrbitIcon(InnerAddIcon32);
export const AddUserIcon24 = createOrbitIcon(InnerAddUserIcon24);
export const AddUserIcon32 = createOrbitIcon(InnerAddUserIcon32);
export const ArrowIcon24 = createOrbitIcon(InnerArrowIcon24);
export const ArrowIcon32 = createOrbitIcon(InnerArrowIcon32);
export const BellIcon24 = createOrbitIcon(InnerBellIcon24);
export const BellIcon32 = createOrbitIcon(InnerBellIcon32);
export const CalendarIcon24 = createOrbitIcon(InnerCalendarIcon24);
export const CalendarIcon32 = createOrbitIcon(InnerCalendarIcon32);
export const CarretIcon24 = createOrbitIcon(InnerCarretIcon24);
export const CarretIcon32 = createOrbitIcon(InnerCarretIcon32);
export const CheckIcon24 = createOrbitIcon(InnerCheckIcon24);
export const CheckIcon32 = createOrbitIcon(InnerCheckIcon32);
export const CheckCircleIcon24 = createOrbitIcon(InnerCheckCircleIcon24);
export const CheckCircleIcon32 = createOrbitIcon(InnerCheckCircleIcon32);
export const ChevronIcon24 = createOrbitIcon(InnerChevronIcon24);
export const ChevronIcon32 = createOrbitIcon(InnerChevronIcon32);
export const CircleIcon24 = createOrbitIcon(InnerCircleIcon24);
export const CircleIcon32 = createOrbitIcon(InnerCircleIcon32);
export const ClearFilterIcon24 = createOrbitIcon(InnerClearFilterIcon24);
export const ClearFilterIcon32 = createOrbitIcon(InnerClearFilterIcon32);
export const CloseIcon24 = createOrbitIcon(InnerCloseIcon24);
export const CloseIcon32 = createOrbitIcon(InnerCloseIcon32);
export const CommunicationIcon24 = createOrbitIcon(InnerCommunicationIcon24);
export const CommunicationIcon32 = createOrbitIcon(InnerCommunicationIcon32);
export const DashIcon24 = createOrbitIcon(InnerDashIcon24);
export const DashIcon32 = createOrbitIcon(InnerDashIcon32);
export const CsvIcon24 = createOrbitIcon(InnerCsvIcon24);
export const CsvIcon32 = createOrbitIcon(InnerCsvIcon32);
export const DoNotDisturbIcon24 = createOrbitIcon(InnerDoNotDisturbIcon24);
export const DoNotDisturbIcon32 = createOrbitIcon(InnerDoNotDisturbIcon32);
export const DownloadIcon24 = createOrbitIcon(InnerDownloadIcon24);
export const DownloadIcon32 = createOrbitIcon(InnerDownloadIcon32);
export const EditIcon24 = createOrbitIcon(InnerEditIcon24);
export const EditIcon32 = createOrbitIcon(InnerEditIcon32);
export const FileIcon24 = createOrbitIcon(InnerFileIcon24);
export const FileIcon32 = createOrbitIcon(InnerFileIcon32);
export const FilterIcon24 = createOrbitIcon(InnerFilterIcon24);
export const FilterIcon32 = createOrbitIcon(InnerFilterIcon32);
export const FlagIcon24 = createOrbitIcon(InnerFlagIcon24);
export const FlagIcon32 = createOrbitIcon(InnerFlagIcon32);
export const FolderIcon24 = createOrbitIcon(InnerFolderIcon24);
export const FolderIcon32 = createOrbitIcon(InnerFolderIcon32);
export const GearIcon24 = createOrbitIcon(InnerGearIcon24);
export const GearIcon32 = createOrbitIcon(InnerGearIcon32);
export const GroupIcon24 = createOrbitIcon(InnerGroupIcon24);
export const GroupIcon32 = createOrbitIcon(InnerGroupIcon32);
export const HelpIcon24 = createOrbitIcon(InnerHelpIcon24);
export const HelpIcon32 = createOrbitIcon(InnerHelpIcon32);
export const HorizontalDotsIcon24 = createOrbitIcon(InnerHorizontalDotsIcon24);
export const HorizontalDotsIcon32 = createOrbitIcon(InnerHorizontalDotsIcon32);
export const InfoIcon24 = createOrbitIcon(InnerInfoIcon24);
export const InfoIcon32 = createOrbitIcon(InnerInfoIcon32);
export const LightbulbIcon24 = createOrbitIcon(InnerLightbulbIcon24);
export const LightbulbIcon32 = createOrbitIcon(InnerLightbulbIcon32);
export const MagnifierIcon24 = createOrbitIcon(InnerMagnifierIcon24);
export const MagnifierIcon32 = createOrbitIcon(InnerMagnifierIcon32);
export const MusicIcon24 = createOrbitIcon(InnerMusicIcon24);
export const MusicIcon32 = createOrbitIcon(InnerMusicIcon32);
export const PdfIcon24 = createOrbitIcon(InnerPdfIcon24);
export const PdfIcon32 = createOrbitIcon(InnerPdfIcon32);
export const PictureIcon24 = createOrbitIcon(InnerPictureIcon24);
export const PictureIcon32 = createOrbitIcon(InnerPictureIcon32);
export const PrinterIcon24 = createOrbitIcon(InnerPrinterIcon24);
export const PrinterIcon32 = createOrbitIcon(InnerPrinterIcon32);
export const PrivacyIcon24 = createOrbitIcon(InnerPrivacyIcon24);
export const ReminderIcon24 = createOrbitIcon(InnerReminderIcon24);
export const ReminderIcon32 = createOrbitIcon(InnerReminderIcon32);
export const RemoveGuestIcon24 = createOrbitIcon(InnerRemoveGuestIcon24);
export const RemoveGuestIcon32 = createOrbitIcon(InnerRemoveGuestIcon32);
export const RemoveUserIcon24 = createOrbitIcon(InnerRemoveUserIcon24);
export const RemoveUserIcon32 = createOrbitIcon(InnerRemoveUserIcon32);
export const SignoutIcon24 = createOrbitIcon(InnerSignoutIcon24);
export const SignoutIcon32 = createOrbitIcon(InnerSignoutIcon32);
export const SortIcon24 = createOrbitIcon(InnerSortIcon24);
export const SortIcon32 = createOrbitIcon(InnerSortIcon32);
export const SlashIcon24 = createOrbitIcon(InnerSlashIcon24);
export const SlashIcon32 = createOrbitIcon(InnerSlashIcon32);
export const TrashIcon24 = createOrbitIcon(InnerTrashIcon24);
export const TrashIcon32 = createOrbitIcon(InnerTrashIcon32);
export const UpDownIcon24 = createOrbitIcon(InnerUpDownIcon24);
export const UpDownIcon32 = createOrbitIcon(InnerUpDownIcon32);
export const VerticalDotsIcon24 = createOrbitIcon(InnerVerticalDotsIcon24);
export const VerticalDotsIcon32 = createOrbitIcon(InnerVerticalDotsIcon32);
export const VideoIcon24 = createOrbitIcon(InnerVideoIcon24);
export const VideoIcon32 = createOrbitIcon(InnerVideoIcon32);
export const WarningIcon24 = createOrbitIcon(InnerWarningIcon24);
export const WarningIcon32 = createOrbitIcon(InnerWarningIcon32);
export const ZipIcon24 = createOrbitIcon(InnerZipIcon24);
export const ZipIcon32 = createOrbitIcon(InnerZipIcon32);

export const AddGuestIcon = createOrbitMultiVariantIcon(InnerAddGuestIcon24, InnerAddGuestIcon32);
export const AddIcon = createOrbitMultiVariantIcon(InnerAddIcon24, InnerAddIcon32);
export const AddUserIcon = createOrbitMultiVariantIcon(InnerAddUserIcon24, InnerAddUserIcon32);
export const ArrowIcon = createOrbitMultiVariantIcon(InnerArrowIcon24, InnerArrowIcon32);
export const BellIcon = createOrbitMultiVariantIcon(InnerBellIcon24, InnerBellIcon32);
export const CalendarIcon = createOrbitMultiVariantIcon(InnerCalendarIcon24, InnerCalendarIcon32);
export const CarretIcon = createOrbitMultiVariantIcon(InnerCarretIcon24, InnerCarretIcon32);
export const CheckIcon = createOrbitMultiVariantIcon(InnerCheckIcon24, InnerCheckIcon32);
export const CheckCircleIcon = createOrbitMultiVariantIcon(InnerCheckCircleIcon24, InnerCheckCircleIcon32);
export const ChevronIcon = createOrbitMultiVariantIcon(InnerChevronIcon24, InnerChevronIcon32);
export const CircleIcon = createOrbitMultiVariantIcon(InnerCircleIcon24, InnerCircleIcon32);
export const ClearFilterIcon = createOrbitMultiVariantIcon(InnerClearFilterIcon24, InnerClearFilterIcon32);
export const CloseIcon = createOrbitMultiVariantIcon(InnerCloseIcon24, InnerCloseIcon32);
export const DashIcon = createOrbitMultiVariantIcon(DashIcon24, DashIcon32);
export const CommunicationIcon = createOrbitMultiVariantIcon(InnerCommunicationIcon24, InnerCommunicationIcon32);
export const CsvIcon = createOrbitMultiVariantIcon(InnerCsvIcon24, InnerCsvIcon32);
export const DoNotDisturbIcon = createOrbitMultiVariantIcon(InnerDoNotDisturbIcon24, InnerDoNotDisturbIcon32);
export const DownloadIcon = createOrbitMultiVariantIcon(InnerDownloadIcon24, InnerDownloadIcon32);
export const EditIcon = createOrbitMultiVariantIcon(InnerEditIcon24, InnerEditIcon32);
export const FileIcon = createOrbitMultiVariantIcon(InnerFileIcon24, InnerFileIcon32);
export const FilterIcon = createOrbitMultiVariantIcon(InnerFilterIcon24, InnerFilterIcon32);
export const FlagIcon = createOrbitMultiVariantIcon(InnerFlagIcon24, InnerFlagIcon32);
export const FolderIcon = createOrbitMultiVariantIcon(InnerFolderIcon24, InnerFolderIcon32);
export const GearIcon = createOrbitMultiVariantIcon(InnerGearIcon24, InnerGearIcon32);
export const GroupIcon = createOrbitMultiVariantIcon(InnerGroupIcon24, InnerGroupIcon32);
export const HelpIcon = createOrbitMultiVariantIcon(InnerHelpIcon24, InnerHelpIcon32);
export const HorizontalDotsIcon = createOrbitMultiVariantIcon(InnerHorizontalDotsIcon24, InnerHorizontalDotsIcon32);
export const InfoIcon = createOrbitMultiVariantIcon(InnerInfoIcon24, InnerInfoIcon32);
export const LightbulbIcon = createOrbitMultiVariantIcon(InnerLightbulbIcon24, InnerLightbulbIcon32);
export const MagnifierIcon = createOrbitMultiVariantIcon(InnerMagnifierIcon24, InnerMagnifierIcon32);
export const MusicIcon = createOrbitMultiVariantIcon(InnerMusicIcon24, InnerMusicIcon32);
export const PdfIcon = createOrbitMultiVariantIcon(InnerPdfIcon24, InnerPdfIcon32);
export const PictureIcon = createOrbitMultiVariantIcon(InnerPictureIcon24, InnerPictureIcon32);
export const PrinterIcon = createOrbitMultiVariantIcon(InnerPrinterIcon24, InnerPrinterIcon32);
export const PrivacyIcon = createOrbitMultiVariantIcon(InnerPrivacyIcon24, InnerPrivacyIcon24);
export const ReminderIcon = createOrbitMultiVariantIcon(InnerReminderIcon24, InnerReminderIcon32);
export const RemoveGuestIcon = createOrbitMultiVariantIcon(InnerRemoveGuestIcon24, InnerRemoveGuestIcon32);
export const RemoveUserIcon = createOrbitMultiVariantIcon(InnerRemoveUserIcon24, InnerRemoveUserIcon32);
export const SignoutIcon = createOrbitMultiVariantIcon(InnerSignoutIcon24, InnerSignoutIcon32);
export const SortIcon = createOrbitMultiVariantIcon(InnerSortIcon24, InnerSortIcon32);
export const SlashIcon = createOrbitMultiVariantIcon(InnerSlashIcon24, InnerSlashIcon32);
export const TrashIcon = createOrbitMultiVariantIcon(InnerTrashIcon24, InnerTrashIcon32);
export const UpDownIcon = createOrbitMultiVariantIcon(InnerUpDownIcon24, InnerUpDownIcon32);
export const VerticalDotsIcon = createOrbitMultiVariantIcon(InnerVerticalDotsIcon24, InnerVerticalDotsIcon32);
export const VideoIcon = createOrbitMultiVariantIcon(InnerVideoIcon24, InnerVideoIcon32);
export const WarningIcon = createOrbitMultiVariantIcon(InnerWarningIcon24, InnerWarningIcon32);
export const ZipIcon = createOrbitMultiVariantIcon(InnerZipIcon24, InnerZipIcon32);
