import { ElementType } from "react";
import { createIcon } from "./Icon";

export * from "./Icon";
export * from "./MultiVariantIcon";
export * from "./IconList";
export * from "./EmbeddedIcon";

function createOrbitIcon(source: ElementType, displayName: string) {
    const Component = createIcon(source);
    Component.displayName = displayName;

    return Component;
}

import { ReactComponent as InnerAddGuestIcon32 } from "@orbit-ui/icons/dist/icon-add-guest-32.svg";
import { ReactComponent as InnerAddIcon32 } from "@orbit-ui/icons/dist/icon-add-32.svg";
import { ReactComponent as InnerAddUserIcon32 } from "@orbit-ui/icons/dist/icon-add-user-32.svg";
import { ReactComponent as InnerArchiveCompleteIcon32 } from "@orbit-ui/icons/dist/icon-archive-complete-32.svg";
import { ReactComponent as InnerArchiveDeletedIcon32 } from "@orbit-ui/icons/dist/icon-archive-deleted-32.svg";
import { ReactComponent as InnerArchiveIcon32 } from "@orbit-ui/icons/dist/icon-archive-32.svg";
import { ReactComponent as InnerArchiveRestoreIcon32 } from "@orbit-ui/icons/dist/icon-archive-restore-32.svg";
import { ReactComponent as InnerArrowDownIcon32 } from "@orbit-ui/icons/dist/icon-arrow-down-32.svg";
import { ReactComponent as InnerArrowDownLeftIcon32 } from "@orbit-ui/icons/dist/icon-arrow-down-left-32.svg";
import { ReactComponent as InnerArrowDownRightIcon32 } from "@orbit-ui/icons/dist/icon-arrow-down-right-32.svg";
import { ReactComponent as InnerArrowIcon32 } from "@orbit-ui/icons/dist/icon-arrow-32.svg";
import { ReactComponent as InnerArrowLeftIcon32 } from "@orbit-ui/icons/dist/icon-arrow-left-32.svg";
import { ReactComponent as InnerArrowLineUpIcon32 } from "@orbit-ui/icons/dist/icon-arrow-line-up-32.svg";
import { ReactComponent as InnerArrowRightIcon32 } from "@orbit-ui/icons/dist/icon-arrow-right-32.svg";
import { ReactComponent as InnerArrowUpIcon32 } from "@orbit-ui/icons/dist/icon-arrow-up-32.svg";
import { ReactComponent as InnerArrowUpLeftIcon32 } from "@orbit-ui/icons/dist/icon-arrow-up-left-32.svg";
import { ReactComponent as InnerArrowUpRightIcon32 } from "@orbit-ui/icons/dist/icon-arrow-up-right-32.svg";
import { ReactComponent as InnerArrowsUpDownIcon32 } from "@orbit-ui/icons/dist/icon-arrows-up-down-32.svg";
import { ReactComponent as InnerCalendarIcon32 } from "@orbit-ui/icons/dist/icon-calendar-32.svg";
import { ReactComponent as InnerCalendarPresetIcon32 } from "@orbit-ui/icons/dist/icon-calendar-preset-32.svg";
import { ReactComponent as InnerCaretDownIcon32 } from "@orbit-ui/icons/dist/icon-caret-down-32.svg";
import { ReactComponent as InnerCaretIcon32 } from "@orbit-ui/icons/dist/icon-caret-32.svg";
import { ReactComponent as InnerCaretLeftIcon32 } from "@orbit-ui/icons/dist/icon-caret-left-32.svg";
import { ReactComponent as InnerCaretRightIcon32 } from "@orbit-ui/icons/dist/icon-caret-right-32.svg";
import { ReactComponent as InnerCaretUpDownIcon32 } from "@orbit-ui/icons/dist/icon-caret-up-down-32.svg";
import { ReactComponent as InnerCaretUpIcon32 } from "@orbit-ui/icons/dist/icon-caret-up-32.svg";
import { ReactComponent as InnerCheckCircleIcon32 } from "@orbit-ui/icons/dist/icon-check-circle-32.svg";
import { ReactComponent as InnerCheckmarkIcon32 } from "@orbit-ui/icons/dist/icon-checkmark-32.svg";
import { ReactComponent as InnerChevronDownIcon32 } from "@orbit-ui/icons/dist/icon-chevron-down-32.svg";
import { ReactComponent as InnerChevronIcon32 } from "@orbit-ui/icons/dist/icon-chevron-32.svg";
import { ReactComponent as InnerChevronLeftIcon32 } from "@orbit-ui/icons/dist/icon-chevron-left-32.svg";
import { ReactComponent as InnerChevronRightIcon32 } from "@orbit-ui/icons/dist/icon-chevron-right-32.svg";
import { ReactComponent as InnerChevronUpDownIcon32 } from "@orbit-ui/icons/dist/icon-chevron-up-down-32.svg";
import { ReactComponent as InnerChevronUpIcon32 } from "@orbit-ui/icons/dist/icon-chevron-up-32.svg";
import { ReactComponent as InnerClearFilterIcon32 } from "@orbit-ui/icons/dist/icon-clear-filter-32.svg";
import { ReactComponent as InnerCloseIcon32 } from "@orbit-ui/icons/dist/icon-close-32.svg";
import { ReactComponent as InnerCrossIcon32 } from "@orbit-ui/icons/dist/icon-cross-32.svg";
import { ReactComponent as InnerDeleteLinkIcon32 } from "@orbit-ui/icons/dist/icon-delete-link-32.svg";
import { ReactComponent as InnerDoNotDisturbIcon32 } from "@orbit-ui/icons/dist/icon-do-not-disturb-32.svg";
import { ReactComponent as InnerDownloadIcon32 } from "@orbit-ui/icons/dist/icon-download-32.svg";
import { ReactComponent as InnerEditIcon32 } from "@orbit-ui/icons/dist/icon-edit-32.svg";
import { ReactComponent as InnerFileIcon32 } from "@orbit-ui/icons/dist/icon-file-32.svg";
import { ReactComponent as InnerFilterIcon32 } from "@orbit-ui/icons/dist/icon-filter-32.svg";
import { ReactComponent as InnerFlagIcon32 } from "@orbit-ui/icons/dist/icon-flag-32.svg";
import { ReactComponent as InnerFolderIcon32 } from "@orbit-ui/icons/dist/icon-folder-32.svg";
import { ReactComponent as InnerGearIcon32 } from "@orbit-ui/icons/dist/icon-gear-32.svg";
import { ReactComponent as InnerGroupIcon32 } from "@orbit-ui/icons/dist/icon-group-32.svg";
import { ReactComponent as InnerGroupSettingIcon32 } from "@orbit-ui/icons/dist/icon-group-setting-32.svg";
import { ReactComponent as InnerGuestIcon32 } from "@orbit-ui/icons/dist/icon-guest-32.svg";
import { ReactComponent as InnerHelpIcon32 } from "@orbit-ui/icons/dist/icon-help-32.svg";
import { ReactComponent as InnerHorizontalDotsIcon32 } from "@orbit-ui/icons/dist/icon-horizontal-dots-32.svg";
import { ReactComponent as InnerInactiveIcon32 } from "@orbit-ui/icons/dist/icon-inactive-32.svg";
import { ReactComponent as InnerInfoIcon32 } from "@orbit-ui/icons/dist/icon-info-32.svg";
import { ReactComponent as InnerKeyIcon32 } from "@orbit-ui/icons/dist/icon-key-32.svg";
import { ReactComponent as InnerLightbulbIcon32 } from "@orbit-ui/icons/dist/icon-lightbulb-32.svg";
import { ReactComponent as InnerLinkIcon32 } from "@orbit-ui/icons/dist/icon-link-32.svg";
import { ReactComponent as InnerMagnifierIcon32 } from "@orbit-ui/icons/dist/icon-magnifier-32.svg";
import { ReactComponent as InnerMailIcon32 } from "@orbit-ui/icons/dist/icon-mail-32.svg";
import { ReactComponent as InnerMismatchIcon32 } from "@orbit-ui/icons/dist/icon-mismatch-32.svg";
import { ReactComponent as InnerMusicFileIcon32 } from "@orbit-ui/icons/dist/icon-music-file-32.svg";
import { ReactComponent as InnerNoGuestIcon32 } from "@orbit-ui/icons/dist/icon-no-guest-32.svg";
import { ReactComponent as InnerNotificationIcon32 } from "@orbit-ui/icons/dist/icon-notification-32.svg";
import { ReactComponent as InnerPdfFileIcon32 } from "@orbit-ui/icons/dist/icon-pdf-file-32.svg";
import { ReactComponent as InnerPictureIcon32 } from "@orbit-ui/icons/dist/icon-picture-32.svg";
import { ReactComponent as InnerPrinterIcon32 } from "@orbit-ui/icons/dist/icon-printer-32.svg";
import { ReactComponent as InnerPrivacyChangedIcon32 } from "@orbit-ui/icons/dist/icon-privacy-changed-32.svg";
import { ReactComponent as InnerPrivacyEditIcon32 } from "@orbit-ui/icons/dist/icon-privacy-edit-32.svg";
import { ReactComponent as InnerPrivacyIcon32 } from "@orbit-ui/icons/dist/icon-privacy-32.svg";
import { ReactComponent as InnerPrivateGroupIcon32 } from "@orbit-ui/icons/dist/icon-private-group-32.svg";
import { ReactComponent as InnerPublicGroupIcon32 } from "@orbit-ui/icons/dist/icon-public-group-32.svg";
import { ReactComponent as InnerRemoveGuestIcon32 } from "@orbit-ui/icons/dist/icon-remove-guest-32.svg";
import { ReactComponent as InnerRemoveUserIcon32 } from "@orbit-ui/icons/dist/icon-remove-user-32.svg";
import { ReactComponent as InnerRestoreIcon32 } from "@orbit-ui/icons/dist/icon-restore-32.svg";
import { ReactComponent as InnerSecurityIcon32 } from "@orbit-ui/icons/dist/icon-security-32.svg";
import { ReactComponent as InnerSettingsIcon32 } from "@orbit-ui/icons/dist/icon-settings-32.svg";
import { ReactComponent as InnerShareIcon32 } from "@orbit-ui/icons/dist/icon-share-32.svg";
import { ReactComponent as InnerSigninIcon32 } from "@orbit-ui/icons/dist/icon-signin-32.svg";
import { ReactComponent as InnerSignoutIcon32 } from "@orbit-ui/icons/dist/icon-signout-32.svg";
import { ReactComponent as InnerTrashboxIcon32 } from "@orbit-ui/icons/dist/icon-trashbox-32.svg";
import { ReactComponent as InnerUploadIcon32 } from "@orbit-ui/icons/dist/icon-upload-32.svg";
import { ReactComponent as InnerUserIcon32 } from "@orbit-ui/icons/dist/icon-user-32.svg";
import { ReactComponent as InnerVerticalDotsIcon32 } from "@orbit-ui/icons/dist/icon-vertical-dots-32.svg";
import { ReactComponent as InnerVideoFileIcon32 } from "@orbit-ui/icons/dist/icon-video-file-32.svg";
import { ReactComponent as InnerViewIcon32 } from "@orbit-ui/icons/dist/icon-view-32.svg";
import { ReactComponent as InnerWarningIcon32 } from "@orbit-ui/icons/dist/icon-warning-32.svg";

export const AddIcon32 = createOrbitIcon(InnerAddIcon32, "AddIcon32");
export const AddGuestIcon32 = createOrbitIcon(InnerAddGuestIcon32, "AddGuestIcon32");
export const AddUserIcon32 = createOrbitIcon(InnerAddUserIcon32, "AddUserIcon32");
export const ArchiveIcon32 = createOrbitIcon(InnerArchiveIcon32, "ArchiveIcon32");
export const ArchiveCompleteIcon32 = createOrbitIcon(InnerArchiveCompleteIcon32, "ArchiveCompleteIcon32");
export const ArchiveDeletedIcon32 = createOrbitIcon(InnerArchiveDeletedIcon32, "ArchiveDeletedIcon32");
export const ArchiveRestoreIcon32 = createOrbitIcon(InnerArchiveRestoreIcon32, "ArchiveRestoreIcon32");
export const ArrowIcon32 = createOrbitIcon(InnerArrowIcon32, "ArrowIcon32");
export const ArrowDownIcon32 = createOrbitIcon(InnerArrowDownIcon32, "ArrowDownIcon32");
export const ArrowDownLeftIcon32 = createOrbitIcon(InnerArrowDownLeftIcon32, "ArrowDownLeftIcon32");
export const ArrowDownRightIcon32 = createOrbitIcon(InnerArrowDownRightIcon32, "ArrowDownRightIcon32");
export const ArrowUpLeftIcon32 = createOrbitIcon(InnerArrowUpLeftIcon32, "ArrowUpLeftIcon32");
export const ArrowUpRightIcon32 = createOrbitIcon(InnerArrowUpRightIcon32, "ArrowUpRightIcon32");
export const ArrowLeftIcon32 = createOrbitIcon(InnerArrowLeftIcon32, "ArrowLeftIcon32");
export const ArrowLineUpIcon32 = createOrbitIcon(InnerArrowLineUpIcon32, "ArrowLineUpIcon32");
export const ArrowRightIcon32 = createOrbitIcon(InnerArrowRightIcon32, "ArrowRightIcon32");
export const ArrowUpIcon32 = createOrbitIcon(InnerArrowUpIcon32, "ArrowUpIcon32");
export const ArrowsUpDownIcon32 = createOrbitIcon(InnerArrowsUpDownIcon32, "ArrowsUpDownIcon32");
export const CalendarIcon32 = createOrbitIcon(InnerCalendarIcon32, "CalendarIcon32");
export const CalendarPresetIcon32 = createOrbitIcon(InnerCalendarPresetIcon32, "CalendarPresetIcon32");
export const CaretIcon32 = createOrbitIcon(InnerCaretIcon32, "CaretIcon32");
export const CaretDownIcon32 = createOrbitIcon(InnerCaretDownIcon32, "CaretDownIcon32");
export const CaretLeftIcon32 = createOrbitIcon(InnerCaretLeftIcon32, "CaretLeftIcon32");
export const CaretRightIcon32 = createOrbitIcon(InnerCaretRightIcon32, "CaretRightIcon32");
export const CaretUpIcon32 = createOrbitIcon(InnerCaretUpIcon32, "CaretUpIcon32");
export const CaretUpDownIcon32 = createOrbitIcon(InnerCaretUpDownIcon32, "CaretUpDownIcon32");
export const CheckCircleIcon32 = createOrbitIcon(InnerCheckCircleIcon32, "CheckCircleIcon32");
export const CheckmarkIcon32 = createOrbitIcon(InnerCheckmarkIcon32, "CheckmarkIcon32");
export const ChevronIcon32 = createOrbitIcon(InnerChevronIcon32, "ChevronIcon32");
export const ChevronUpIcon32 = createOrbitIcon(InnerChevronUpIcon32, "ChevronUpIcon32");
export const ChevronDownIcon32 = createOrbitIcon(InnerChevronDownIcon32, "ChevronDownIcon32");
export const ChevronUpDownIcon32 = createOrbitIcon(InnerChevronUpDownIcon32, "ChevronUpDownIcon32");
export const ChevronLeftIcon32 = createOrbitIcon(InnerChevronLeftIcon32, "ChevronLeftIcon32");
export const ChevronRightIcon32 = createOrbitIcon(InnerChevronRightIcon32, "ChevronRightIcon32");
export const ClearFilterIcon32 = createOrbitIcon(InnerClearFilterIcon32, "ClearFilterIcon32");
export const CloseIcon32 = createOrbitIcon(InnerCloseIcon32, "CloseIcon32");
export const CrossIcon32 = createOrbitIcon(InnerCrossIcon32, "CrossIcon32");
export const DeleteLinkIcon32 = createOrbitIcon(InnerDeleteLinkIcon32, "DeleteLinkIcon32");
export const DoNotDisturbIcon32 = createOrbitIcon(InnerDoNotDisturbIcon32, "DoNotDisturbIcon32");
export const DownloadIcon32 = createOrbitIcon(InnerDownloadIcon32, "DownloadIcon32");
export const EditIcon32 = createOrbitIcon(InnerEditIcon32, "EditIcon32");
export const FileIcon32 = createOrbitIcon(InnerFileIcon32, "FileIcon32");
export const FilterIcon32 = createOrbitIcon(InnerFilterIcon32, "FilterIcon32");
export const FlagIcon32 = createOrbitIcon(InnerFlagIcon32, "FlagIcon32");
export const FolderIcon32 = createOrbitIcon(InnerFolderIcon32, "FolderIcon32");
export const GearIcon32 = createOrbitIcon(InnerGearIcon32, "GearIcon32");
export const GroupIcon32 = createOrbitIcon(InnerGroupIcon32, "GroupIcon32");
export const GroupSettingIcon32 = createOrbitIcon(InnerGroupSettingIcon32, "GroupSettingIcon32");
export const GuestIcon32 = createOrbitIcon(InnerGuestIcon32, "GuestIcon32");
export const HelpIcon32 = createOrbitIcon(InnerHelpIcon32, "HelpIcon32");
export const HorizontalDotsIcon32 = createOrbitIcon(InnerHorizontalDotsIcon32, "HorizontalDotsIcon32");
export const InactiveIcon32 = createOrbitIcon(InnerInactiveIcon32, "InactiveIcon32");
export const InfoIcon32 = createOrbitIcon(InnerInfoIcon32, "InfoIcon32");
export const KeyIcon32 = createOrbitIcon(InnerKeyIcon32, "KeyIcon32");
export const LightbulbIcon32 = createOrbitIcon(InnerLightbulbIcon32, "LightbulbIcon32");
export const LinkIcon32 = createOrbitIcon(InnerLinkIcon32, "LinkIcon32");
export const MagnifierIcon32 = createOrbitIcon(InnerMagnifierIcon32, "MagnifierIcon32");
export const MailIcon32 = createOrbitIcon(InnerMailIcon32, "MailIcon32");
export const MismatchIcon32 = createOrbitIcon(InnerMismatchIcon32, "MismatchIcon32");
export const MusicFileIcon32 = createOrbitIcon(InnerMusicFileIcon32, "MusicFileIcon32");
export const NoGuestIcon32 = createOrbitIcon(InnerNoGuestIcon32, "NoGuestIcon32");
export const NotificationIcon32 = createOrbitIcon(InnerNotificationIcon32, "NotificationIcon32");
export const PdfFileIcon32 = createOrbitIcon(InnerPdfFileIcon32, "PdfFileIcon32");
export const PictureIcon32 = createOrbitIcon(InnerPictureIcon32, "PictureIcon32");
export const PrinterIcon32 = createOrbitIcon(InnerPrinterIcon32, "PrinterIcon32");
export const PrivacyIcon32 = createOrbitIcon(InnerPrivacyIcon32, "PrivacyIcon32");
export const PrivacyChangedIcon32 = createOrbitIcon(InnerPrivacyChangedIcon32, "PrivacyChangedIcon32");
export const PrivacyEditIcon32 = createOrbitIcon(InnerPrivacyEditIcon32, "PrivacyEditIcon32");
export const PrivateGroupIcon32 = createOrbitIcon(InnerPrivateGroupIcon32, "PrivateGroupIcon32");
export const PublicGroupIcon32 = createOrbitIcon(InnerPublicGroupIcon32, "PublicGroupIcon32");
export const RemoveGuestIcon32 = createOrbitIcon(InnerRemoveGuestIcon32, "RemoveGuestIcon32");
export const RemoveUserIcon32 = createOrbitIcon(InnerRemoveUserIcon32, "RemoveUserIcon32");
export const RestoreIcon32 = createOrbitIcon(InnerRestoreIcon32, "RestoreIcon32");
export const SecurityIcon32 = createOrbitIcon(InnerSecurityIcon32, "SecurityIcon32");
export const SettingsIcon32 = createOrbitIcon(InnerSettingsIcon32, "SettingsIcon32");
export const ShareIcon32 = createOrbitIcon(InnerShareIcon32, "ShareIcon32");
export const SigninIcon32 = createOrbitIcon(InnerSigninIcon32, "SigninIcon32");
export const SignoutIcon32 = createOrbitIcon(InnerSignoutIcon32, "SignoutIcon32");
export const TrashboxIcon32 = createOrbitIcon(InnerTrashboxIcon32, "TrashboxIcon32");
export const UserIcon32 = createOrbitIcon(InnerUserIcon32, "UserIcon32");
export const UploadIcon32 = createOrbitIcon(InnerUploadIcon32, "UploadIcon32");
export const VerticalDotsIcon32 = createOrbitIcon(InnerVerticalDotsIcon32, "VerticalDotseIcon32");
export const VideoFileIcon32 = createOrbitIcon(InnerVideoFileIcon32, "VideoFileIcon32");
export const ViewIcon32 = createOrbitIcon(InnerViewIcon32, "ViewIcon32");
export const WarningIcon32 = createOrbitIcon(InnerWarningIcon32, "WarningIcon32");

export const AddIcon = createOrbitIcon(InnerAddIcon32, "AddIcon");
export const AddGuestIcon = createOrbitIcon(InnerAddGuestIcon32, "AddGuestIcon");
export const AddUserIcon = createOrbitIcon(InnerAddUserIcon32, "AddUserIcon");
export const ArchiveIcon = createOrbitIcon(InnerArchiveIcon32, "ArchiveIcon");
export const ArchiveCompleteIcon = createOrbitIcon(InnerArchiveCompleteIcon32, "ArchiveCompleteIcon");
export const ArchiveDeletedIcon = createOrbitIcon(InnerArchiveDeletedIcon32, "ArchiveDeletedIcon");
export const ArchiveRestoreIcon = createOrbitIcon(InnerArchiveRestoreIcon32, "ArchiveRestoreIcon");
export const ArrowIcon = createOrbitIcon(InnerArrowIcon32, "ArrowIcon");
export const ArrowDownIcon = createOrbitIcon(InnerArrowDownIcon32, "ArrowDownIcon");
export const ArrowDownLeftIcon = createOrbitIcon(InnerArrowDownLeftIcon32, "ArrowDownLeftIcon");
export const ArrowDownRightIcon = createOrbitIcon(InnerArrowDownRightIcon32, "ArrowDownRightIcon");
export const ArrowUpLeftIcon = createOrbitIcon(InnerArrowUpLeftIcon32, "ArrowUpLeftIcon");
export const ArrowUpRightIcon = createOrbitIcon(InnerArrowUpRightIcon32, "ArrowUpRightIcon");
export const ArrowLeftIcon = createOrbitIcon(InnerArrowLeftIcon32, "ArrowLeftIcon");
export const ArrowLineUpIcon = createOrbitIcon(InnerArrowLineUpIcon32, "ArrowLineUpIcon");
export const ArrowRightIcon = createOrbitIcon(InnerArrowRightIcon32, "ArrowRightIcon");
export const ArrowUpIcon = createOrbitIcon(InnerArrowUpIcon32, "ArrowUpIcon");
export const ArrowsUpDownIcon = createOrbitIcon(InnerArrowsUpDownIcon32, "ArrowsUpDownIcon");
export const CalendarIcon = createOrbitIcon(InnerCalendarIcon32, "CalendarIcon");
export const CalendarPresetIcon = createOrbitIcon(InnerCalendarPresetIcon32, "CalendarPresetIcon");
export const CaretIcon = createOrbitIcon(InnerCaretIcon32, "CaretIcon");
export const CaretDownIcon = createOrbitIcon(InnerCaretDownIcon32, "CaretDownIcon");
export const CaretLeftIcon = createOrbitIcon(InnerCaretLeftIcon32, "CaretLeftIcon");
export const CaretRightIcon = createOrbitIcon(InnerCaretRightIcon32, "CaretRightIcon");
export const CaretUpIcon = createOrbitIcon(InnerCaretUpIcon32, "CaretUpIcon");
export const CaretUpDownIcon = createOrbitIcon(InnerCaretUpDownIcon32, "CaretUpDownIcon");
export const CheckCircleIcon = createOrbitIcon(InnerCheckCircleIcon32, "CheckCircleIcon");
export const CheckmarkIcon = createOrbitIcon(InnerCheckmarkIcon32, "CheckmarkIcon");
export const ChevronIcon = createOrbitIcon(InnerChevronIcon32, "ChevronIcon");
export const ChevronUpIcon = createOrbitIcon(InnerChevronUpIcon32, "ChevronUpIcon");
export const ChevronDownIcon = createOrbitIcon(InnerChevronDownIcon32, "ChevronDownIcon");
export const ChevronUpDownIcon = createOrbitIcon(InnerChevronUpDownIcon32, "ChevronUpDownIcon");
export const ChevronLeftIcon = createOrbitIcon(InnerChevronLeftIcon32, "ChevronLeftIcon");
export const ChevronRightIcon = createOrbitIcon(InnerChevronRightIcon32, "ChevronRightIcon");
export const ClearFilterIcon = createOrbitIcon(InnerClearFilterIcon32, "ClearFilterIcon");
export const CloseIcon = createOrbitIcon(InnerCloseIcon32, "CloseIcon");
export const CrossIcon = createOrbitIcon(InnerCrossIcon32, "CrossIcon");
export const DeleteLinkIcon = createOrbitIcon(InnerDeleteLinkIcon32, "DeleteLinkIcon");
export const DoNotDisturbIcon = createOrbitIcon(InnerDoNotDisturbIcon32, "DoNotDisturbIcon");
export const DownloadIcon = createOrbitIcon(InnerDownloadIcon32, "DownloadIcon");
export const EditIcon = createOrbitIcon(InnerEditIcon32, "EditIcon");
export const FileIcon = createOrbitIcon(InnerFileIcon32, "FileIcon");
export const FilterIcon = createOrbitIcon(InnerFilterIcon32, "FilterIcon");
export const FlagIcon = createOrbitIcon(InnerFlagIcon32, "FlagIcon");
export const FolderIcon = createOrbitIcon(InnerFolderIcon32, "FolderIcon");
export const GearIcon = createOrbitIcon(InnerGearIcon32, "GearIcon");
export const GroupIcon = createOrbitIcon(InnerGroupIcon32, "GroupIcon");
export const GroupSettingIcon = createOrbitIcon(InnerGroupSettingIcon32, "GroupSettingIcon");
export const GuestIcon = createOrbitIcon(InnerGuestIcon32, "GuestIcon");
export const HorizontalDotsIcon = createOrbitIcon(InnerHorizontalDotsIcon32, "HorizontalDotsIcon");
export const HelpIcon = createOrbitIcon(InnerHelpIcon32, "HelpIcon");
export const InactiveIcon = createOrbitIcon(InnerInactiveIcon32, "InactiveIcon");
export const InfoIcon = createOrbitIcon(InnerInfoIcon32, "InfoIcon");
export const KeyIcon = createOrbitIcon(InnerKeyIcon32, "KeyIcon");
export const LightbulbIcon = createOrbitIcon(InnerLightbulbIcon32, "LightbulbIcon");
export const LinkIcon = createOrbitIcon(InnerLinkIcon32, "LinkIcon");
export const MagnifierIcon = createOrbitIcon(InnerMagnifierIcon32, "MagnifierIcon");
export const MailIcon = createOrbitIcon(InnerMailIcon32, "MailIcon");
export const MismatchIcon = createOrbitIcon(InnerMismatchIcon32, "MismatchIcon");
export const MusicFileIcon = createOrbitIcon(InnerMusicFileIcon32, "MusicFileIcon");
export const NoGuestIcon = createOrbitIcon(InnerNoGuestIcon32, "NoGuestIcon");
export const NotificationIcon = createOrbitIcon(InnerNotificationIcon32, "NotificationIcon");
export const PdfFileIcon = createOrbitIcon(InnerPdfFileIcon32, "PdfFileIcon");
export const PictureIcon = createOrbitIcon(InnerPictureIcon32, "PictureIcon");
export const PrinterIcon = createOrbitIcon(InnerPrinterIcon32, "PrinterIcon");
export const PrivacyIcon = createOrbitIcon(InnerPrivacyIcon32, "PrivacyIcon");
export const PrivacyChangedIcon = createOrbitIcon(InnerPrivacyChangedIcon32, "PrivacyChangedIcon");
export const PrivacyEditIcon = createOrbitIcon(InnerPrivacyEditIcon32, "PrivacyEditIcon");
export const PrivateGroupIcon = createOrbitIcon(InnerPrivateGroupIcon32, "PrivateGroupIcon");
export const PublicGroupIcon = createOrbitIcon(InnerPublicGroupIcon32, "PublicGroupIcon");
export const RemoveGuestIcon = createOrbitIcon(InnerRemoveGuestIcon32, "RemoveGuestIcon");
export const RemoveUserIcon = createOrbitIcon(InnerRemoveUserIcon32, "RemoveUserIcon");
export const RestoreIcon = createOrbitIcon(InnerRestoreIcon32, "RestoreIcon");
export const SecurityIcon = createOrbitIcon(InnerSecurityIcon32, "SecurityIcon");
export const SettingsIcon = createOrbitIcon(InnerSettingsIcon32, "SettingsIcon");
export const ShareIcon = createOrbitIcon(InnerShareIcon32, "ShareIcon");
export const SigninIcon = createOrbitIcon(InnerSigninIcon32, "SigninIcon");
export const SignoutIcon = createOrbitIcon(InnerSignoutIcon32, "SignoutIcon");
export const TrashboxIcon = createOrbitIcon(InnerTrashboxIcon32, "TrashboxIcon");
export const UploadIcon = createOrbitIcon(InnerUploadIcon32, "UploadIcon");
export const UserIcon = createOrbitIcon(InnerUserIcon32, "UserIcon");
export const VerticalDotsIcon = createOrbitIcon(InnerVerticalDotsIcon32, "VerticalDotsIcon");
export const VideoFileIcon = createOrbitIcon(InnerVideoFileIcon32, "VideoFileIcon");
export const ViewIcon = createOrbitIcon(InnerViewIcon32, "ViewIcon");
export const WarningIcon = createOrbitIcon(InnerWarningIcon32, "WarningIcon");
