import { Icon, MultiVariantIcon } from "./icon";

function createOrbitIcon(source) {
    return Icon.create(source);
}

function createOrbitMultiVariantIcon(source24, source32) {
    return MultiVariantIcon.create(source24, source32);
}

import { ReactComponent as InnerAddIcon24 } from "@orbit-ui/icons/dist/icon-add-24.svg";
import { ReactComponent as InnerAddIcon32 } from "@orbit-ui/icons/dist/icon-add-32.svg";
import { ReactComponent as InnerAddUserIcon32 } from "@orbit-ui/icons/dist/icon-add-user-32.svg";
import { ReactComponent as InnerArrowIcon24 } from "@orbit-ui/icons/dist/icon-arrow-24.svg";
import { ReactComponent as InnerArrowIcon32 } from "@orbit-ui/icons/dist/icon-arrow-32.svg";
import { ReactComponent as InnerCalendarIcon24 } from "@orbit-ui/icons/dist/icon-calendar-24.svg";
import { ReactComponent as InnerCalendarIcon32 } from "@orbit-ui/icons/dist/icon-calendar-32.svg";
import { ReactComponent as InnerCheckIcon24 } from "@orbit-ui/icons/dist/icon-check-24.svg";
import { ReactComponent as InnerCheckIcon32 } from "@orbit-ui/icons/dist/icon-check-32.svg";
import { ReactComponent as InnerCircleIcon24 } from "@orbit-ui/icons/dist/icon-circle-24.svg";
import { ReactComponent as InnerCircleIcon32 } from "@orbit-ui/icons/dist/icon-circle-32.svg";
import { ReactComponent as InnerClearFilterIcon24 } from "@orbit-ui/icons/dist/icon-clear-filter-24.svg";
import { ReactComponent as InnerClearFilterIcon32 } from "@orbit-ui/icons/dist/icon-clear-filter-32.svg";
import { ReactComponent as InnerCloseIcon24 } from "@orbit-ui/icons/dist/icon-close-24.svg";
import { ReactComponent as InnerCloseIcon32 } from "@orbit-ui/icons/dist/icon-close-32.svg";
import { ReactComponent as InnerCommunicationIcon32 } from "@orbit-ui/icons/dist/icon-communication-32.svg";
import { ReactComponent as InnerCompareIcon24 } from "@orbit-ui/icons/dist/icon-compare-24.svg";
import { ReactComponent as InnerCompareIcon32 } from "@orbit-ui/icons/dist/icon-compare-32.svg";
import { ReactComponent as InnerCsvIcon32 } from "@orbit-ui/icons/dist/icon-csv-32.svg";
import { ReactComponent as InnerDoNotDisturbIcon32 } from "@orbit-ui/icons/dist/icon-do-not-disturb-32.svg";
import { ReactComponent as InnerDownloadIcon32 } from "@orbit-ui/icons/dist/icon-download-32.svg";
import { ReactComponent as InnerEditIcon32 } from "@orbit-ui/icons/dist/icon-edit-32.svg";
import { ReactComponent as InnerFileIcon32 } from "@orbit-ui/icons/dist/icon-file-32.svg";
import { ReactComponent as InnerFolderIcon32 } from "@orbit-ui/icons/dist/icon-folder-32.svg";
import { ReactComponent as InnerGarbageIcon32 } from "@orbit-ui/icons/dist/icon-garbage-32.svg";
import { ReactComponent as InnerGearIcon32 } from "@orbit-ui/icons/dist/icon-gear-32.svg";
import { ReactComponent as InnerGroupIcon32 } from "@orbit-ui/icons/dist/icon-group-32.svg";
import { ReactComponent as InnerHelpIcon24 } from "@orbit-ui/icons/dist/icon-help-24.svg";
import { ReactComponent as InnerHelpIcon32 } from "@orbit-ui/icons/dist/icon-help-32.svg";
import { ReactComponent as InnerHorizontalDotsIcon32 } from "@orbit-ui/icons/dist/icon-horizontal-dots-32.svg";
import { ReactComponent as InnerImageIcon32 } from "@orbit-ui/icons/dist/icon-image-32.svg";
import { ReactComponent as InnerInfoIcon24 } from "@orbit-ui/icons/dist/icon-info-24.svg";
import { ReactComponent as InnerInfoIcon32 } from "@orbit-ui/icons/dist/icon-info-32.svg";
import { ReactComponent as InnerLightbulbIcon24 } from "@orbit-ui/icons/dist/icon-lightbulb-24.svg";
import { ReactComponent as InnerLightbulbIcon32 } from "@orbit-ui/icons/dist/icon-lightbulb-32.svg";
import { ReactComponent as InnerMagnifierIcon32 } from "@orbit-ui/icons/dist/icon-magnifier-32.svg";
import { ReactComponent as InnerMusicIcon32 } from "@orbit-ui/icons/dist/icon-music-32.svg";
import { ReactComponent as InnerNotificationIcon24 } from "@orbit-ui/icons/dist/icon-notification-24.svg";
import { ReactComponent as InnerNotificationIcon32 } from "@orbit-ui/icons/dist/icon-notification-32.svg";
import { ReactComponent as InnerPdfIcon32 } from "@orbit-ui/icons/dist/icon-pdf-32.svg";
import { ReactComponent as InnerPrinterIcon24 } from "@orbit-ui/icons/dist/icon-printer-24.svg";
import { ReactComponent as InnerPrinterIcon32 } from "@orbit-ui/icons/dist/icon-printer-32.svg";
import { ReactComponent as InnerPrivacyIcon24 } from "@orbit-ui/icons/dist/icon-privacy-24.svg";
import { ReactComponent as InnerReminderIcon32 } from "@orbit-ui/icons/dist/icon-reminder-32.svg";
import { ReactComponent as InnerRemoveUserIcon32 } from "@orbit-ui/icons/dist/icon-remove-user-32.svg";
import { ReactComponent as InnerSignoutIcon24 } from "@orbit-ui/icons/dist/icon-signout-24.svg";
import { ReactComponent as InnerSignoutIcon32 } from "@orbit-ui/icons/dist/icon-signout-32.svg";
import { ReactComponent as InnerSortingIcon24 } from "@orbit-ui/icons/dist/icon-sorting-24.svg";
import { ReactComponent as InnerSortingIcon32 } from "@orbit-ui/icons/dist/icon-sorting-32.svg";
import { ReactComponent as InnerVariationIcon24 } from "@orbit-ui/icons/dist/icon-variation-24.svg";
import { ReactComponent as InnerVariationIcon32 } from "@orbit-ui/icons/dist/icon-variation-32.svg";
import { ReactComponent as InnerVerticalDotsIcon32 } from "@orbit-ui/icons/dist/icon-vertical-dots-32.svg";
import { ReactComponent as InnerVideoIcon32 } from "@orbit-ui/icons/dist/icon-video-32.svg";
import { ReactComponent as InnerWarningIcon24 } from "@orbit-ui/icons/dist/icon-warning-24.svg";
import { ReactComponent as InnerWarningIcon32 } from "@orbit-ui/icons/dist/icon-warning-32.svg";
import { ReactComponent as InnerZipIcon32 } from "@orbit-ui/icons/dist/icon-zip-32.svg";

export const AddIcon24 = createOrbitIcon(InnerAddIcon24);
export const AddIcon32 = createOrbitIcon(InnerAddIcon32);
export const AddUserIcon32 = createOrbitIcon(InnerAddUserIcon32);
export const ArrowIcon24 = createOrbitIcon(InnerArrowIcon24);
export const ArrowIcon32 = createOrbitIcon(InnerArrowIcon32);
export const CalendarIcon24 = createOrbitIcon(InnerCalendarIcon24);
export const CalendarIcon32 = createOrbitIcon(InnerCalendarIcon32);
export const CheckIcon24 = createOrbitIcon(InnerCheckIcon24);
export const CheckIcon32 = createOrbitIcon(InnerCheckIcon32);
export const CircleIcon24 = createOrbitIcon(InnerCircleIcon24);
export const CircleIcon32 = createOrbitIcon(InnerCircleIcon32);
export const ClearFilterIcon24 = createOrbitIcon(InnerClearFilterIcon24);
export const ClearFilterIcon32 = createOrbitIcon(InnerClearFilterIcon32);
export const CloseIcon24 = createOrbitIcon(InnerCloseIcon24);
export const CloseIcon32 = createOrbitIcon(InnerCloseIcon32);
export const CommunicationIcon32 = createOrbitIcon(InnerCommunicationIcon32);
export const CompareIcon24 = createOrbitIcon(InnerCompareIcon24);
export const CompareIcon32 = createOrbitIcon(InnerCompareIcon32);
export const CsvIcon32 = createOrbitIcon(InnerCsvIcon32);
export const DoNotDisturbIcon32 = createOrbitIcon(InnerDoNotDisturbIcon32);
export const DownloadIcon32 = createOrbitIcon(InnerDownloadIcon32);
export const EditIcon32 = createOrbitIcon(InnerEditIcon32);
export const FileIcon32 = createOrbitIcon(InnerFileIcon32);
export const FolderIcon32 = createOrbitIcon(InnerFolderIcon32);
export const GarbageIcon32 = createOrbitIcon(InnerGarbageIcon32);
export const GearIcon32 = createOrbitIcon(InnerGearIcon32);
export const GroupIcon32 = createOrbitIcon(InnerGroupIcon32);
export const HelpIcon24 = createOrbitIcon(InnerHelpIcon24);
export const HelpIcon32 = createOrbitIcon(InnerHelpIcon32);
export const HorizontalDotsIcon32 = createOrbitIcon(InnerHorizontalDotsIcon32);
export const ImageIcon32 = createOrbitIcon(InnerImageIcon32);
export const InfoIcon24 = createOrbitIcon(InnerInfoIcon24);
export const InfoIcon32 = createOrbitIcon(InnerInfoIcon32);
export const LightbulbIcon24 = createOrbitIcon(InnerLightbulbIcon24);
export const LightbulbIcon32 = createOrbitIcon(InnerLightbulbIcon32);
export const MagnifierIcon32 = createOrbitIcon(InnerMagnifierIcon32);
export const MusicIcon32 = createOrbitIcon(InnerMusicIcon32);
export const NotificationIcon24 = createOrbitIcon(InnerNotificationIcon24);
export const NotificationIcon32 = createOrbitIcon(InnerNotificationIcon32);
export const PdfIcon32 = createOrbitIcon(InnerPdfIcon32);
export const PrinterIcon24 = createOrbitIcon(InnerPrinterIcon24);
export const PrinterIcon32 = createOrbitIcon(InnerPrinterIcon32);
export const PrivacyIcon24 = createOrbitIcon(InnerPrivacyIcon24);
export const ReminderIcon32 = createOrbitIcon(InnerReminderIcon32);
export const RemoveUserIcon32 = createOrbitIcon(InnerRemoveUserIcon32);
export const SignoutIcon24 = createOrbitIcon(InnerSignoutIcon24);
export const SignoutIcon32 = createOrbitIcon(InnerSignoutIcon32);
export const SortingIcon24 = createOrbitIcon(InnerSortingIcon24);
export const SortingIcon32 = createOrbitIcon(InnerSortingIcon32);
export const VariationIcon24 = createOrbitIcon(InnerVariationIcon24);
export const VariationIcon32 = createOrbitIcon(InnerVariationIcon32);
export const VerticalDotsIcon32 = createOrbitIcon(InnerVerticalDotsIcon32);
export const VideoIcon32 = createOrbitIcon(InnerVideoIcon32);
export const WarningIcon24 = createOrbitIcon(InnerWarningIcon24);
export const WarningIcon32 = createOrbitIcon(InnerWarningIcon32);
export const ZipIcon32 = createOrbitIcon(InnerZipIcon32);

export const AddIcon = createOrbitMultiVariantIcon(InnerAddIcon24, InnerAddIcon32);
export const AddUserIcon = createOrbitMultiVariantIcon(InnerAddUserIcon32, InnerAddUserIcon32);
export const ArrowIcon = createOrbitMultiVariantIcon(InnerArrowIcon24, InnerArrowIcon32);
export const CalendarIcon = createOrbitMultiVariantIcon(InnerCalendarIcon24, InnerCalendarIcon32);
export const CheckIcon = createOrbitMultiVariantIcon(InnerCheckIcon24, InnerCheckIcon32);
export const CircleIcon = createOrbitMultiVariantIcon(InnerCircleIcon24, InnerCircleIcon32);
export const ClearFilterIcon = createOrbitMultiVariantIcon(InnerClearFilterIcon24, InnerClearFilterIcon32);
export const CloseIcon = createOrbitMultiVariantIcon(InnerCloseIcon24, InnerCloseIcon32);
export const CommunicationIcon = createOrbitMultiVariantIcon(InnerCommunicationIcon32, InnerCommunicationIcon32);
export const CompareIcon = createOrbitMultiVariantIcon(InnerCompareIcon24, InnerCompareIcon32);
export const CsvIcon = createOrbitMultiVariantIcon(InnerCsvIcon32, InnerCsvIcon32);
export const DoNotDisturbIcon = createOrbitMultiVariantIcon(InnerDoNotDisturbIcon32, InnerDoNotDisturbIcon32);
export const DownloadIcon = createOrbitMultiVariantIcon(InnerDownloadIcon32, InnerDownloadIcon32);
export const EditIcon = createOrbitMultiVariantIcon(InnerEditIcon32, InnerEditIcon32);
export const FileIcon = createOrbitMultiVariantIcon(InnerFileIcon32, InnerFileIcon32);
export const FolderIcon = createOrbitMultiVariantIcon(InnerFolderIcon32, InnerFolderIcon32);
export const GarbageIcon = createOrbitMultiVariantIcon(InnerGarbageIcon32, InnerGarbageIcon32);
export const GearIcon = createOrbitMultiVariantIcon(InnerGearIcon32, InnerGearIcon32);
export const GroupIcon = createOrbitMultiVariantIcon(InnerGroupIcon32, InnerGroupIcon32);
export const HelpIcon = createOrbitMultiVariantIcon(InnerHelpIcon24, InnerHelpIcon32);
export const HorizontalDotsIcon = createOrbitMultiVariantIcon(InnerHorizontalDotsIcon32, InnerHorizontalDotsIcon32);
export const ImageIcon = createOrbitMultiVariantIcon(InnerImageIcon32, InnerImageIcon32);
export const InfoIcon = createOrbitMultiVariantIcon(InnerInfoIcon24, InnerInfoIcon32);
export const LightbulbIcon = createOrbitMultiVariantIcon(InnerLightbulbIcon24, InnerLightbulbIcon32);
export const MagnifierIcon = createOrbitMultiVariantIcon(InnerMagnifierIcon32, InnerMagnifierIcon32);
export const MusicIcon = createOrbitMultiVariantIcon(InnerMusicIcon32, InnerMusicIcon32);
export const NotificationIcon = createOrbitMultiVariantIcon(InnerNotificationIcon24, InnerNotificationIcon32);
export const PdfIcon = createOrbitMultiVariantIcon(InnerPdfIcon32, InnerPdfIcon32);
export const PrinterIcon = createOrbitMultiVariantIcon(InnerPrinterIcon24, InnerPrinterIcon32);
export const PrivacyIcon = createOrbitMultiVariantIcon(InnerPrivacyIcon24, InnerPrivacyIcon24);
export const ReminderIcon = createOrbitMultiVariantIcon(InnerReminderIcon32, InnerReminderIcon32);
export const RemoveUserIcon = createOrbitMultiVariantIcon(InnerRemoveUserIcon32, InnerRemoveUserIcon32);
export const SignoutIcon = createOrbitMultiVariantIcon(InnerSignoutIcon24, InnerSignoutIcon32);
export const SortingIcon = createOrbitMultiVariantIcon(InnerSortingIcon24, InnerSortingIcon32);
export const VariationIcon = createOrbitMultiVariantIcon(InnerVariationIcon24, InnerVariationIcon32);
export const VerticalDotsIcon = createOrbitMultiVariantIcon(InnerVerticalDotsIcon32, InnerVerticalDotsIcon32);
export const VideoIcon = createOrbitMultiVariantIcon(InnerVideoIcon32, InnerVideoIcon32);
export const WarningIcon = createOrbitMultiVariantIcon(InnerWarningIcon24, InnerWarningIcon32);
export const ZipIcon = createOrbitMultiVariantIcon(InnerZipIcon32, InnerZipIcon32);
