import {
    LAST_12_MONTHS_PRESET,
    LAST_3_MONTHS_PRESET,
    LAST_6_MONTHS_PRESET,
    LAST_MONTH_PRESET,
    LAST_WEEK_PRESET
} from "@react-components/date-picker";

export const DEFAULT_PRESETS_OPTIONS = {
    LAST_WEEK_PRESET: LAST_WEEK_PRESET,
    LAST_MONTH_PRESET: LAST_MONTH_PRESET,
    LAST_3_MONTHS_PRESET: LAST_3_MONTHS_PRESET,
    LAST_6_MONTHS_PRESET: LAST_6_MONTHS_PRESET,
    LAST_12_MONTHS_PRESET: LAST_12_MONTHS_PRESET
};
