/*
* THIS FILE IS GENERATED. DO NOT EDIT IT.
* To re-generate the icons, run the yarn generate-icons-components command in the components project.
*/

/* eslint-disable */
import { createOrbitIcon, createOrbitMultiVariantIcon } from "../createOrbitIcon";

import { ReactComponent as InnerAddIcon24 } from "./AddIcon24";
import { ReactComponent as InnerAddIcon32 } from "./AddIcon32";
import { ReactComponent as InnerArrowIcon24 } from "./ArrowIcon24";
import { ReactComponent as InnerArrowIcon32 } from "./ArrowIcon32";
import { ReactComponent as InnerCalendarIcon24 } from "./CalendarIcon24";
import { ReactComponent as InnerCalendarIcon32 } from "./CalendarIcon32";
import { ReactComponent as InnerCaretIcon24 } from "./CaretIcon24";
import { ReactComponent as InnerCaretIcon32 } from "./CaretIcon32";
import { ReactComponent as InnerCheckIcon24 } from "./CheckIcon24";
import { ReactComponent as InnerCheckIcon32 } from "./CheckIcon32";
import { ReactComponent as InnerCheckCircleIcon24 } from "./CheckCircleIcon24";
import { ReactComponent as InnerCheckCircleIcon32 } from "./CheckCircleIcon32";
import { ReactComponent as InnerChevronIcon24 } from "./ChevronIcon24";
import { ReactComponent as InnerChevronIcon32 } from "./ChevronIcon32";
import { ReactComponent as InnerClearFilterIcon24 } from "./ClearFilterIcon24";
import { ReactComponent as InnerClearFilterIcon32 } from "./ClearFilterIcon32";
import { ReactComponent as InnerCrossIcon24 } from "./CrossIcon24";
import { ReactComponent as InnerCrossIcon32 } from "./CrossIcon32";
import { ReactComponent as InnerCsvIcon24 } from "./CsvIcon24";
import { ReactComponent as InnerCsvIcon32 } from "./CsvIcon32";
import { ReactComponent as InnerDashIcon24 } from "./DashIcon24";
import { ReactComponent as InnerDashIcon32 } from "./DashIcon32";
import { ReactComponent as InnerDotIcon24 } from "./DotIcon24";
import { ReactComponent as InnerDotIcon32 } from "./DotIcon32";
import { ReactComponent as InnerDownloadIcon24 } from "./DownloadIcon24";
import { ReactComponent as InnerDownloadIcon32 } from "./DownloadIcon32";
import { ReactComponent as InnerEditIcon24 } from "./EditIcon24";
import { ReactComponent as InnerEditIcon32 } from "./EditIcon32";
import { ReactComponent as InnerEmailIcon24 } from "./EmailIcon24";
import { ReactComponent as InnerEmailIcon32 } from "./EmailIcon32";
import { ReactComponent as InnerEmailReminderIcon24 } from "./EmailReminderIcon24";
import { ReactComponent as InnerEmailReminderIcon32 } from "./EmailReminderIcon32";
import { ReactComponent as InnerEyeIcon24 } from "./EyeIcon24";
import { ReactComponent as InnerEyeIcon32 } from "./EyeIcon32";
import { ReactComponent as InnerFileIcon24 } from "./FileIcon24";
import { ReactComponent as InnerFileIcon32 } from "./FileIcon32";
import { ReactComponent as InnerFilterIcon24 } from "./FilterIcon24";
import { ReactComponent as InnerFilterIcon32 } from "./FilterIcon32";
import { ReactComponent as InnerFlagIcon24 } from "./FlagIcon24";
import { ReactComponent as InnerFlagIcon32 } from "./FlagIcon32";
import { ReactComponent as InnerFolderIcon24 } from "./FolderIcon24";
import { ReactComponent as InnerFolderIcon32 } from "./FolderIcon32";
import { ReactComponent as InnerGearIcon24 } from "./GearIcon24";
import { ReactComponent as InnerGearIcon32 } from "./GearIcon32";
import { ReactComponent as InnerGroupIcon24 } from "./GroupIcon24";
import { ReactComponent as InnerGroupIcon32 } from "./GroupIcon32";
import { ReactComponent as InnerGuestAddIcon24 } from "./GuestAddIcon24";
import { ReactComponent as InnerGuestAddIcon32 } from "./GuestAddIcon32";
import { ReactComponent as InnerGuestRemoveIcon24 } from "./GuestRemoveIcon24";
import { ReactComponent as InnerGuestRemoveIcon32 } from "./GuestRemoveIcon32";
import { ReactComponent as InnerHelpIcon24 } from "./HelpIcon24";
import { ReactComponent as InnerHelpIcon32 } from "./HelpIcon32";
import { ReactComponent as InnerHorizontalDotsIcon24 } from "./HorizontalDotsIcon24";
import { ReactComponent as InnerHorizontalDotsIcon32 } from "./HorizontalDotsIcon32";
import { ReactComponent as InnerImageIcon24 } from "./ImageIcon24";
import { ReactComponent as InnerImageIcon32 } from "./ImageIcon32";
import { ReactComponent as InnerInfoIcon24 } from "./InfoIcon24";
import { ReactComponent as InnerInfoIcon32 } from "./InfoIcon32";
import { ReactComponent as InnerLightbulbIcon24 } from "./LightbulbIcon24";
import { ReactComponent as InnerLightbulbIcon32 } from "./LightbulbIcon32";
import { ReactComponent as InnerMagnifierIcon24 } from "./MagnifierIcon24";
import { ReactComponent as InnerMagnifierIcon32 } from "./MagnifierIcon32";
import { ReactComponent as InnerMusicIcon24 } from "./MusicIcon24";
import { ReactComponent as InnerMusicIcon32 } from "./MusicIcon32";
import { ReactComponent as InnerNotificationIcon24 } from "./NotificationIcon24";
import { ReactComponent as InnerNotificationIcon32 } from "./NotificationIcon32";
import { ReactComponent as InnerNotificationOffIcon24 } from "./NotificationOffIcon24";
import { ReactComponent as InnerNotificationOffIcon32 } from "./NotificationOffIcon32";
import { ReactComponent as InnerPdfIcon24 } from "./PdfIcon24";
import { ReactComponent as InnerPdfIcon32 } from "./PdfIcon32";
import { ReactComponent as InnerPrinterIcon24 } from "./PrinterIcon24";
import { ReactComponent as InnerPrinterIcon32 } from "./PrinterIcon32";
import { ReactComponent as InnerPrivacyIcon24 } from "./PrivacyIcon24";
import { ReactComponent as InnerPrivacyIcon32 } from "./PrivacyIcon32";
import { ReactComponent as InnerSettingsIcon24 } from "./SettingsIcon24";
import { ReactComponent as InnerSettingsIcon32 } from "./SettingsIcon32";
import { ReactComponent as InnerSignoutIcon24 } from "./SignoutIcon24";
import { ReactComponent as InnerSignoutIcon32 } from "./SignoutIcon32";
import { ReactComponent as InnerSlashIcon24 } from "./SlashIcon24";
import { ReactComponent as InnerSlashIcon32 } from "./SlashIcon32";
import { ReactComponent as InnerSortIcon24 } from "./SortIcon24";
import { ReactComponent as InnerSortIcon32 } from "./SortIcon32";
import { ReactComponent as InnerTrashIcon24 } from "./TrashIcon24";
import { ReactComponent as InnerTrashIcon32 } from "./TrashIcon32";
import { ReactComponent as InnerUserAddIcon24 } from "./UserAddIcon24";
import { ReactComponent as InnerUserAddIcon32 } from "./UserAddIcon32";
import { ReactComponent as InnerUserRemoveIcon24 } from "./UserRemoveIcon24";
import { ReactComponent as InnerUserRemoveIcon32 } from "./UserRemoveIcon32";
import { ReactComponent as InnerVerticalDotsIcon24 } from "./VerticalDotsIcon24";
import { ReactComponent as InnerVerticalDotsIcon32 } from "./VerticalDotsIcon32";
import { ReactComponent as InnerVideoIcon24 } from "./VideoIcon24";
import { ReactComponent as InnerVideoIcon32 } from "./VideoIcon32";
import { ReactComponent as InnerWarningIcon24 } from "./WarningIcon24";
import { ReactComponent as InnerWarningIcon32 } from "./WarningIcon32";
import { ReactComponent as InnerZipIcon24 } from "./ZipIcon24";
import { ReactComponent as InnerZipIcon32 } from "./ZipIcon32";

export const AddIcon24 = createOrbitIcon(InnerAddIcon24, "AddIcon24");
export const AddIcon32 = createOrbitIcon(InnerAddIcon32, "AddIcon32");
export const ArrowIcon24 = createOrbitIcon(InnerArrowIcon24, "ArrowIcon24");
export const ArrowIcon32 = createOrbitIcon(InnerArrowIcon32, "ArrowIcon32");
export const CalendarIcon24 = createOrbitIcon(InnerCalendarIcon24, "CalendarIcon24");
export const CalendarIcon32 = createOrbitIcon(InnerCalendarIcon32, "CalendarIcon32");
export const CaretIcon24 = createOrbitIcon(InnerCaretIcon24, "CaretIcon24");
export const CaretIcon32 = createOrbitIcon(InnerCaretIcon32, "CaretIcon32");
export const CheckIcon24 = createOrbitIcon(InnerCheckIcon24, "CheckIcon24");
export const CheckIcon32 = createOrbitIcon(InnerCheckIcon32, "CheckIcon32");
export const CheckCircleIcon24 = createOrbitIcon(InnerCheckCircleIcon24, "CheckCircleIcon24");
export const CheckCircleIcon32 = createOrbitIcon(InnerCheckCircleIcon32, "CheckCircleIcon32");
export const ChevronIcon24 = createOrbitIcon(InnerChevronIcon24, "ChevronIcon24");
export const ChevronIcon32 = createOrbitIcon(InnerChevronIcon32, "ChevronIcon32");
export const ClearFilterIcon24 = createOrbitIcon(InnerClearFilterIcon24, "ClearFilterIcon24");
export const ClearFilterIcon32 = createOrbitIcon(InnerClearFilterIcon32, "ClearFilterIcon32");
export const CrossIcon24 = createOrbitIcon(InnerCrossIcon24, "CrossIcon24");
export const CrossIcon32 = createOrbitIcon(InnerCrossIcon32, "CrossIcon32");
export const CsvIcon24 = createOrbitIcon(InnerCsvIcon24, "CsvIcon24");
export const CsvIcon32 = createOrbitIcon(InnerCsvIcon32, "CsvIcon32");
export const DashIcon24 = createOrbitIcon(InnerDashIcon24, "DashIcon24");
export const DashIcon32 = createOrbitIcon(InnerDashIcon32, "DashIcon32");
export const DotIcon24 = createOrbitIcon(InnerDotIcon24, "DotIcon24");
export const DotIcon32 = createOrbitIcon(InnerDotIcon32, "DotIcon32");
export const DownloadIcon24 = createOrbitIcon(InnerDownloadIcon24, "DownloadIcon24");
export const DownloadIcon32 = createOrbitIcon(InnerDownloadIcon32, "DownloadIcon32");
export const EditIcon24 = createOrbitIcon(InnerEditIcon24, "EditIcon24");
export const EditIcon32 = createOrbitIcon(InnerEditIcon32, "EditIcon32");
export const EmailIcon24 = createOrbitIcon(InnerEmailIcon24, "EmailIcon24");
export const EmailIcon32 = createOrbitIcon(InnerEmailIcon32, "EmailIcon32");
export const EmailReminderIcon24 = createOrbitIcon(InnerEmailReminderIcon24, "EmailReminderIcon24");
export const EmailReminderIcon32 = createOrbitIcon(InnerEmailReminderIcon32, "EmailReminderIcon32");
export const EyeIcon24 = createOrbitIcon(InnerEyeIcon24, "EyeIcon24");
export const EyeIcon32 = createOrbitIcon(InnerEyeIcon32, "EyeIcon32");
export const FileIcon24 = createOrbitIcon(InnerFileIcon24, "FileIcon24");
export const FileIcon32 = createOrbitIcon(InnerFileIcon32, "FileIcon32");
export const FilterIcon24 = createOrbitIcon(InnerFilterIcon24, "FilterIcon24");
export const FilterIcon32 = createOrbitIcon(InnerFilterIcon32, "FilterIcon32");
export const FlagIcon24 = createOrbitIcon(InnerFlagIcon24, "FlagIcon24");
export const FlagIcon32 = createOrbitIcon(InnerFlagIcon32, "FlagIcon32");
export const FolderIcon24 = createOrbitIcon(InnerFolderIcon24, "FolderIcon24");
export const FolderIcon32 = createOrbitIcon(InnerFolderIcon32, "FolderIcon32");
export const GearIcon24 = createOrbitIcon(InnerGearIcon24, "GearIcon24");
export const GearIcon32 = createOrbitIcon(InnerGearIcon32, "GearIcon32");
export const GroupIcon24 = createOrbitIcon(InnerGroupIcon24, "GroupIcon24");
export const GroupIcon32 = createOrbitIcon(InnerGroupIcon32, "GroupIcon32");
export const GuestAddIcon24 = createOrbitIcon(InnerGuestAddIcon24, "GuestAddIcon24");
export const GuestAddIcon32 = createOrbitIcon(InnerGuestAddIcon32, "GuestAddIcon32");
export const GuestRemoveIcon24 = createOrbitIcon(InnerGuestRemoveIcon24, "GuestRemoveIcon24");
export const GuestRemoveIcon32 = createOrbitIcon(InnerGuestRemoveIcon32, "GuestRemoveIcon32");
export const HelpIcon24 = createOrbitIcon(InnerHelpIcon24, "HelpIcon24");
export const HelpIcon32 = createOrbitIcon(InnerHelpIcon32, "HelpIcon32");
export const HorizontalDotsIcon24 = createOrbitIcon(InnerHorizontalDotsIcon24, "HorizontalDotsIcon24");
export const HorizontalDotsIcon32 = createOrbitIcon(InnerHorizontalDotsIcon32, "HorizontalDotsIcon32");
export const ImageIcon24 = createOrbitIcon(InnerImageIcon24, "ImageIcon24");
export const ImageIcon32 = createOrbitIcon(InnerImageIcon32, "ImageIcon32");
export const InfoIcon24 = createOrbitIcon(InnerInfoIcon24, "InfoIcon24");
export const InfoIcon32 = createOrbitIcon(InnerInfoIcon32, "InfoIcon32");
export const LightbulbIcon24 = createOrbitIcon(InnerLightbulbIcon24, "LightbulbIcon24");
export const LightbulbIcon32 = createOrbitIcon(InnerLightbulbIcon32, "LightbulbIcon32");
export const MagnifierIcon24 = createOrbitIcon(InnerMagnifierIcon24, "MagnifierIcon24");
export const MagnifierIcon32 = createOrbitIcon(InnerMagnifierIcon32, "MagnifierIcon32");
export const MusicIcon24 = createOrbitIcon(InnerMusicIcon24, "MusicIcon24");
export const MusicIcon32 = createOrbitIcon(InnerMusicIcon32, "MusicIcon32");
export const NotificationIcon24 = createOrbitIcon(InnerNotificationIcon24, "NotificationIcon24");
export const NotificationIcon32 = createOrbitIcon(InnerNotificationIcon32, "NotificationIcon32");
export const NotificationOffIcon24 = createOrbitIcon(InnerNotificationOffIcon24, "NotificationOffIcon24");
export const NotificationOffIcon32 = createOrbitIcon(InnerNotificationOffIcon32, "NotificationOffIcon32");
export const PdfIcon24 = createOrbitIcon(InnerPdfIcon24, "PdfIcon24");
export const PdfIcon32 = createOrbitIcon(InnerPdfIcon32, "PdfIcon32");
export const PrinterIcon24 = createOrbitIcon(InnerPrinterIcon24, "PrinterIcon24");
export const PrinterIcon32 = createOrbitIcon(InnerPrinterIcon32, "PrinterIcon32");
export const PrivacyIcon24 = createOrbitIcon(InnerPrivacyIcon24, "PrivacyIcon24");
export const PrivacyIcon32 = createOrbitIcon(InnerPrivacyIcon32, "PrivacyIcon32");
export const SettingsIcon24 = createOrbitIcon(InnerSettingsIcon24, "SettingsIcon24");
export const SettingsIcon32 = createOrbitIcon(InnerSettingsIcon32, "SettingsIcon32");
export const SignoutIcon24 = createOrbitIcon(InnerSignoutIcon24, "SignoutIcon24");
export const SignoutIcon32 = createOrbitIcon(InnerSignoutIcon32, "SignoutIcon32");
export const SlashIcon24 = createOrbitIcon(InnerSlashIcon24, "SlashIcon24");
export const SlashIcon32 = createOrbitIcon(InnerSlashIcon32, "SlashIcon32");
export const SortIcon24 = createOrbitIcon(InnerSortIcon24, "SortIcon24");
export const SortIcon32 = createOrbitIcon(InnerSortIcon32, "SortIcon32");
export const TrashIcon24 = createOrbitIcon(InnerTrashIcon24, "TrashIcon24");
export const TrashIcon32 = createOrbitIcon(InnerTrashIcon32, "TrashIcon32");
export const UserAddIcon24 = createOrbitIcon(InnerUserAddIcon24, "UserAddIcon24");
export const UserAddIcon32 = createOrbitIcon(InnerUserAddIcon32, "UserAddIcon32");
export const UserRemoveIcon24 = createOrbitIcon(InnerUserRemoveIcon24, "UserRemoveIcon24");
export const UserRemoveIcon32 = createOrbitIcon(InnerUserRemoveIcon32, "UserRemoveIcon32");
export const VerticalDotsIcon24 = createOrbitIcon(InnerVerticalDotsIcon24, "VerticalDotsIcon24");
export const VerticalDotsIcon32 = createOrbitIcon(InnerVerticalDotsIcon32, "VerticalDotsIcon32");
export const VideoIcon24 = createOrbitIcon(InnerVideoIcon24, "VideoIcon24");
export const VideoIcon32 = createOrbitIcon(InnerVideoIcon32, "VideoIcon32");
export const WarningIcon24 = createOrbitIcon(InnerWarningIcon24, "WarningIcon24");
export const WarningIcon32 = createOrbitIcon(InnerWarningIcon32, "WarningIcon32");
export const ZipIcon24 = createOrbitIcon(InnerZipIcon24, "ZipIcon24");
export const ZipIcon32 = createOrbitIcon(InnerZipIcon32, "ZipIcon32");

export const AddIcon = createOrbitMultiVariantIcon(InnerAddIcon24, InnerAddIcon32, "AddIcon");
export const ArrowIcon = createOrbitMultiVariantIcon(InnerArrowIcon24, InnerArrowIcon32, "ArrowIcon");
export const CalendarIcon = createOrbitMultiVariantIcon(InnerCalendarIcon24, InnerCalendarIcon32, "CalendarIcon");
export const CaretIcon = createOrbitMultiVariantIcon(InnerCaretIcon24, InnerCaretIcon32, "CaretIcon");
export const CheckIcon = createOrbitMultiVariantIcon(InnerCheckIcon24, InnerCheckIcon32, "CheckIcon");
export const CheckCircleIcon = createOrbitMultiVariantIcon(InnerCheckCircleIcon24, InnerCheckCircleIcon32, "CheckCircleIcon");
export const ChevronIcon = createOrbitMultiVariantIcon(InnerChevronIcon24, InnerChevronIcon32, "ChevronIcon");
export const ClearFilterIcon = createOrbitMultiVariantIcon(InnerClearFilterIcon24, InnerClearFilterIcon32, "ClearFilterIcon");
export const CrossIcon = createOrbitMultiVariantIcon(InnerCrossIcon24, InnerCrossIcon32, "CrossIcon");
export const CsvIcon = createOrbitMultiVariantIcon(InnerCsvIcon24, InnerCsvIcon32, "CsvIcon");
export const DashIcon = createOrbitMultiVariantIcon(InnerDashIcon24, InnerDashIcon32, "DashIcon");
export const DotIcon = createOrbitMultiVariantIcon(InnerDotIcon24, InnerDotIcon32, "DotIcon");
export const DownloadIcon = createOrbitMultiVariantIcon(InnerDownloadIcon24, InnerDownloadIcon32, "DownloadIcon");
export const EditIcon = createOrbitMultiVariantIcon(InnerEditIcon24, InnerEditIcon32, "EditIcon");
export const EmailIcon = createOrbitMultiVariantIcon(InnerEmailIcon24, InnerEmailIcon32, "EmailIcon");
export const EmailReminderIcon = createOrbitMultiVariantIcon(InnerEmailReminderIcon24, InnerEmailReminderIcon32, "EmailReminderIcon");
export const EyeIcon = createOrbitMultiVariantIcon(InnerEyeIcon24, InnerEyeIcon32, "EyeIcon");
export const FileIcon = createOrbitMultiVariantIcon(InnerFileIcon24, InnerFileIcon32, "FileIcon");
export const FilterIcon = createOrbitMultiVariantIcon(InnerFilterIcon24, InnerFilterIcon32, "FilterIcon");
export const FlagIcon = createOrbitMultiVariantIcon(InnerFlagIcon24, InnerFlagIcon32, "FlagIcon");
export const FolderIcon = createOrbitMultiVariantIcon(InnerFolderIcon24, InnerFolderIcon32, "FolderIcon");
export const GearIcon = createOrbitMultiVariantIcon(InnerGearIcon24, InnerGearIcon32, "GearIcon");
export const GroupIcon = createOrbitMultiVariantIcon(InnerGroupIcon24, InnerGroupIcon32, "GroupIcon");
export const GuestAddIcon = createOrbitMultiVariantIcon(InnerGuestAddIcon24, InnerGuestAddIcon32, "GuestAddIcon");
export const GuestRemoveIcon = createOrbitMultiVariantIcon(InnerGuestRemoveIcon24, InnerGuestRemoveIcon32, "GuestRemoveIcon");
export const HelpIcon = createOrbitMultiVariantIcon(InnerHelpIcon24, InnerHelpIcon32, "HelpIcon");
export const HorizontalDotsIcon = createOrbitMultiVariantIcon(InnerHorizontalDotsIcon24, InnerHorizontalDotsIcon32, "HorizontalDotsIcon");
export const ImageIcon = createOrbitMultiVariantIcon(InnerImageIcon24, InnerImageIcon32, "ImageIcon");
export const InfoIcon = createOrbitMultiVariantIcon(InnerInfoIcon24, InnerInfoIcon32, "InfoIcon");
export const LightbulbIcon = createOrbitMultiVariantIcon(InnerLightbulbIcon24, InnerLightbulbIcon32, "LightbulbIcon");
export const MagnifierIcon = createOrbitMultiVariantIcon(InnerMagnifierIcon24, InnerMagnifierIcon32, "MagnifierIcon");
export const MusicIcon = createOrbitMultiVariantIcon(InnerMusicIcon24, InnerMusicIcon32, "MusicIcon");
export const NotificationIcon = createOrbitMultiVariantIcon(InnerNotificationIcon24, InnerNotificationIcon32, "NotificationIcon");
export const NotificationOffIcon = createOrbitMultiVariantIcon(InnerNotificationOffIcon24, InnerNotificationOffIcon32, "NotificationOffIcon");
export const PdfIcon = createOrbitMultiVariantIcon(InnerPdfIcon24, InnerPdfIcon32, "PdfIcon");
export const PrinterIcon = createOrbitMultiVariantIcon(InnerPrinterIcon24, InnerPrinterIcon32, "PrinterIcon");
export const PrivacyIcon = createOrbitMultiVariantIcon(InnerPrivacyIcon24, InnerPrivacyIcon32, "PrivacyIcon");
export const SettingsIcon = createOrbitMultiVariantIcon(InnerSettingsIcon24, InnerSettingsIcon32, "SettingsIcon");
export const SignoutIcon = createOrbitMultiVariantIcon(InnerSignoutIcon24, InnerSignoutIcon32, "SignoutIcon");
export const SlashIcon = createOrbitMultiVariantIcon(InnerSlashIcon24, InnerSlashIcon32, "SlashIcon");
export const SortIcon = createOrbitMultiVariantIcon(InnerSortIcon24, InnerSortIcon32, "SortIcon");
export const TrashIcon = createOrbitMultiVariantIcon(InnerTrashIcon24, InnerTrashIcon32, "TrashIcon");
export const UserAddIcon = createOrbitMultiVariantIcon(InnerUserAddIcon24, InnerUserAddIcon32, "UserAddIcon");
export const UserRemoveIcon = createOrbitMultiVariantIcon(InnerUserRemoveIcon24, InnerUserRemoveIcon32, "UserRemoveIcon");
export const VerticalDotsIcon = createOrbitMultiVariantIcon(InnerVerticalDotsIcon24, InnerVerticalDotsIcon32, "VerticalDotsIcon");
export const VideoIcon = createOrbitMultiVariantIcon(InnerVideoIcon24, InnerVideoIcon32, "VideoIcon");
export const WarningIcon = createOrbitMultiVariantIcon(InnerWarningIcon24, InnerWarningIcon32, "WarningIcon");
export const ZipIcon = createOrbitMultiVariantIcon(InnerZipIcon24, InnerZipIcon32, "ZipIcon");
/* eslint-enable */
