/*
* THIS FILE IS GENERATED. DO NOT EDIT IT.
* To re-generate the icons, run the yarn generate-icons-components command in the components project.
*/

/* eslint-disable */
import { createOrbitIcon } from "../createOrbitIcon";

import { ReactComponent as InnerAddMajorIcon } from "./AddMajorIcon24";
import { ReactComponent as InnerAlertMajorIcon } from "./AlertMajorIcon24";
import { ReactComponent as InnerAppAccountMajorIcon } from "./AppAccountMajorIcon24";
import { ReactComponent as InnerAppActivityMajorIcon } from "./AppActivityMajorIcon24";
import { ReactComponent as InnerAppApricotBotMajorIcon } from "./AppApricotBotMajorIcon24";
import { ReactComponent as InnerAppArchivesMajorIcon } from "./AppArchivesMajorIcon24";
import { ReactComponent as InnerAppArchivingMajorIcon } from "./AppArchivingMajorIcon24";
import { ReactComponent as InnerAppArchivingMinorIcon } from "./AppArchivingMinorIcon24";
import { ReactComponent as InnerAppAskOwnersMajorIcon } from "./AppAskOwnersMajorIcon24";
import { ReactComponent as InnerAppAskOwnersMinorIcon } from "./AppAskOwnersMinorIcon24";
import { ReactComponent as InnerAppBurgerMajorIcon } from "./AppBurgerMajorIcon24";
import { ReactComponent as InnerAppCalendarMajorIcon } from "./AppCalendarMajorIcon24";
import { ReactComponent as InnerAppChannelMajorIcon } from "./AppChannelMajorIcon24";
import { ReactComponent as InnerAppChannelMinorIcon } from "./AppChannelMinorIcon24";
import { ReactComponent as InnerAppChevronUpDownMajorIcon } from "./AppChevronUpDownMajorIcon24";
import { ReactComponent as InnerAppChevronUpDownMinorIcon } from "./AppChevronUpDownMinorIcon24";
import { ReactComponent as InnerAppCloudCopyMajorIcon } from "./AppCloudCopyMajorIcon24";
import { ReactComponent as InnerAppCopyToOneDriveMajorIcon } from "./AppCopyToOneDriveMajorIcon24";
import { ReactComponent as InnerAppDashboardMajorIcon } from "./AppDashboardMajorIcon24";
import { ReactComponent as InnerAppDotMajorIcon } from "./AppDotMajorIcon24";
import { ReactComponent as InnerAppDuplicateMajorIcon } from "./AppDuplicateMajorIcon24";
import { ReactComponent as InnerAppExternalLinkMajorIcon } from "./AppExternalLinkMajorIcon24";
import { ReactComponent as InnerAppExternalReviewReviewStartedIcon } from "./AppExternalReviewReviewStartedIcon24";
import { ReactComponent as InnerAppFolderMajorIcon } from "./AppFolderMajorIcon24";
import { ReactComponent as InnerAppGrabMajorIcon } from "./AppGrabMajorIcon24";
import { ReactComponent as InnerAppGuestAllowedMajorIcon } from "./AppGuestAllowedMajorIcon24";
import { ReactComponent as InnerAppGuestNotAllowedMajorIcon } from "./AppGuestNotAllowedMajorIcon24";
import { ReactComponent as InnerAppHelpCircleMajorIcon } from "./AppHelpCircleMajorIcon24";
import { ReactComponent as InnerAppHomeMajorIcon } from "./AppHomeMajorIcon24";
import { ReactComponent as InnerAppIconUserPlusMinorIcon } from "./AppIconUserPlusMinorIcon24";
import { ReactComponent as InnerAppInactiveMajorIcon } from "./AppInactiveMajorIcon24";
import { ReactComponent as InnerAppKeepMajorIcon } from "./AppKeepMajorIcon24";
import { ReactComponent as InnerAppKeepMinorIcon } from "./AppKeepMinorIcon24";
import { ReactComponent as InnerAppKeyMajorIcon } from "./AppKeyMajorIcon24";
import { ReactComponent as InnerAppLinkMajorIcon } from "./AppLinkMajorIcon24";
import { ReactComponent as InnerAppLinkRemoveMajorIcon } from "./AppLinkRemoveMajorIcon24";
import { ReactComponent as InnerAppManageColumnsMajorIcon } from "./AppManageColumnsMajorIcon24";
import { ReactComponent as InnerAppManageMajorIcon } from "./AppManageMajorIcon24";
import { ReactComponent as InnerAppMigrationMajorIcon } from "./AppMigrationMajorIcon24";
import { ReactComponent as InnerAppPencilMajorIcon } from "./AppPencilMajorIcon24";
import { ReactComponent as InnerAppPlaceholderMajorIcon } from "./AppPlaceholderMajorIcon24";
import { ReactComponent as InnerAppPlaceholderMinorIcon } from "./AppPlaceholderMinorIcon24";
import { ReactComponent as InnerAppPoliciesMajorIcon } from "./AppPoliciesMajorIcon24";
import { ReactComponent as InnerAppPrivacyPublicMajorIcon } from "./AppPrivacyPublicMajorIcon24";
import { ReactComponent as InnerAppProvisioningMajorIcon } from "./AppProvisioningMajorIcon24";
import { ReactComponent as InnerAppRevertMajorIcon } from "./AppRevertMajorIcon24";
import { ReactComponent as InnerAppRobotMajorIcon } from "./AppRobotMajorIcon24";
import { ReactComponent as InnerAppRobotMinorIcon } from "./AppRobotMinorIcon24";
import { ReactComponent as InnerAppSharingAnyoneMajorIcon } from "./AppSharingAnyoneMajorIcon24";
import { ReactComponent as InnerAppSharingExistingGuestsMajorIcon } from "./AppSharingExistingGuestsMajorIcon24";
import { ReactComponent as InnerAppSharingNewExistingGuestsMajorIcon } from "./AppSharingNewExistingGuestsMajorIcon24";
import { ReactComponent as InnerAppSharingNoExternalSharingIcon } from "./AppSharingNoExternalSharingIcon24";
import { ReactComponent as InnerAppSigninMajorIcon } from "./AppSigninMajorIcon24";
import { ReactComponent as InnerAppTagAddMajorIcon } from "./AppTagAddMajorIcon24";
import { ReactComponent as InnerAppTagAddMinorIcon } from "./AppTagAddMinorIcon24";
import { ReactComponent as InnerAppTagMajorIcon } from "./AppTagMajorIcon24";
import { ReactComponent as InnerAppTagNoTagMajorIcon } from "./AppTagNoTagMajorIcon24";
import { ReactComponent as InnerAppTagNoTagMinorIcon } from "./AppTagNoTagMinorIcon24";
import { ReactComponent as InnerAppTagPurposeMajorIcon } from "./AppTagPurposeMajorIcon24";
import { ReactComponent as InnerAppTagSensitivityMajorIcon } from "./AppTagSensitivityMajorIcon24";
import { ReactComponent as InnerAppUserMajorIcon } from "./AppUserMajorIcon24";
import { ReactComponent as InnerAppUserMinorIcon } from "./AppUserMinorIcon24";
import { ReactComponent as InnerAppUserPlusMajorIcon } from "./AppUserPlusMajorIcon24";
import { ReactComponent as InnerArrowMajorIcon } from "./ArrowMajorIcon24";
import { ReactComponent as InnerArrowMinorIcon } from "./ArrowMinorIcon24";
import { ReactComponent as InnerCalendarMajorIcon } from "./CalendarMajorIcon24";
import { ReactComponent as InnerCheckMajorIcon } from "./CheckMajorIcon24";
import { ReactComponent as InnerCheckMinorIcon } from "./CheckMinorIcon24";
import { ReactComponent as InnerChevronMajorIcon } from "./ChevronMajorIcon24";
import { ReactComponent as InnerChevronMinorIcon } from "./ChevronMinorIcon24";
import { ReactComponent as InnerCrossMajorIcon } from "./CrossMajorIcon24";
import { ReactComponent as InnerCrossMinorIcon } from "./CrossMinorIcon24";
import { ReactComponent as InnerDownloadMajorIcon } from "./DownloadMajorIcon24";
import { ReactComponent as InnerEmailMajorIcon } from "./EmailMajorIcon24";
import { ReactComponent as InnerEyeMajorIcon } from "./EyeMajorIcon24";
import { ReactComponent as InnerFileCsvMajorIcon } from "./FileCsvMajorIcon24";
import { ReactComponent as InnerFileMajorIcon } from "./FileMajorIcon24";
import { ReactComponent as InnerFileMusicMajorIcon } from "./FileMusicMajorIcon24";
import { ReactComponent as InnerFilePdfMajorIcon } from "./FilePdfMajorIcon24";
import { ReactComponent as InnerFileVideoMajorIcon } from "./FileVideoMajorIcon24";
import { ReactComponent as InnerFileZipMajorIcon } from "./FileZipMajorIcon24";
import { ReactComponent as InnerFilterMajorIcon } from "./FilterMajorIcon24";
import { ReactComponent as InnerFolderMajorIcon } from "./FolderMajorIcon24";
import { ReactComponent as InnerGearMajorIcon } from "./GearMajorIcon24";
import { ReactComponent as InnerGroupMajorIcon } from "./GroupMajorIcon24";
import { ReactComponent as InnerGuestRemoveMajorIcon } from "./GuestRemoveMajorIcon24";
import { ReactComponent as InnerHelpMajorIcon } from "./HelpMajorIcon24";
import { ReactComponent as InnerHorizontalDotsMajorIcon } from "./HorizontalDotsMajorIcon24";
import { ReactComponent as InnerImageMajorIcon } from "./ImageMajorIcon24";
import { ReactComponent as InnerInfoCircleMajorIcon } from "./InfoCircleMajorIcon24";
import { ReactComponent as InnerInfoCircleMinorIcon } from "./InfoCircleMinorIcon24";
import { ReactComponent as InnerLightbulbMajorIcon } from "./LightbulbMajorIcon24";
import { ReactComponent as InnerMagnifierMajorIcon } from "./MagnifierMajorIcon24";
import { ReactComponent as InnerNotificationMajorIcon } from "./NotificationMajorIcon24";
import { ReactComponent as InnerNotificationOffMajorIcon } from "./NotificationOffMajorIcon24";
import { ReactComponent as InnerPencilMajorIcon } from "./PencilMajorIcon24";
import { ReactComponent as InnerPlaceholderMajorIcon } from "./PlaceholderMajorIcon24";
import { ReactComponent as InnerPrivacyPrivateMajorIcon } from "./PrivacyPrivateMajorIcon24";
import { ReactComponent as InnerSignoutMajorIcon } from "./SignoutMajorIcon24";
import { ReactComponent as InnerSortMajorIcon } from "./SortMajorIcon24";
import { ReactComponent as InnerStarFillMajorIcon } from "./StarFillMajorIcon24";
import { ReactComponent as InnerStarOutlineMajorIcon } from "./StarOutlineMajorIcon24";
import { ReactComponent as InnerTrashMajorIcon } from "./TrashMajorIcon24";
import { ReactComponent as InnerTrashMinorIcon } from "./TrashMinorIcon24";
import { ReactComponent as InnerUserAddMajorIcon } from "./UserAddMajorIcon24";
import { ReactComponent as InnerUserAddMinorIcon } from "./UserAddMinorIcon24";
import { ReactComponent as InnerVerticalDotsMajorIcon } from "./VerticalDotsMajorIcon24";
import { ReactComponent as InnerWarningMajorIcon } from "./WarningMajorIcon24";
import { ReactComponent as InnerWarningMinorIcon } from "./WarningMinorIcon24";

export const AddMajorIcon = createOrbitIcon(InnerAddMajorIcon, "AddMajorIcon");
export const AlertMajorIcon = createOrbitIcon(InnerAlertMajorIcon, "AlertMajorIcon");
export const AppAccountMajorIcon = createOrbitIcon(InnerAppAccountMajorIcon, "AppAccountMajorIcon");
export const AppActivityMajorIcon = createOrbitIcon(InnerAppActivityMajorIcon, "AppActivityMajorIcon");
export const AppApricotBotMajorIcon = createOrbitIcon(InnerAppApricotBotMajorIcon, "AppApricotBotMajorIcon");
export const AppArchivesMajorIcon = createOrbitIcon(InnerAppArchivesMajorIcon, "AppArchivesMajorIcon");
export const AppArchivingMajorIcon = createOrbitIcon(InnerAppArchivingMajorIcon, "AppArchivingMajorIcon");
export const AppArchivingMinorIcon = createOrbitIcon(InnerAppArchivingMinorIcon, "AppArchivingMinorIcon");
export const AppAskOwnersMajorIcon = createOrbitIcon(InnerAppAskOwnersMajorIcon, "AppAskOwnersMajorIcon");
export const AppAskOwnersMinorIcon = createOrbitIcon(InnerAppAskOwnersMinorIcon, "AppAskOwnersMinorIcon");
export const AppBurgerMajorIcon = createOrbitIcon(InnerAppBurgerMajorIcon, "AppBurgerMajorIcon");
export const AppCalendarMajorIcon = createOrbitIcon(InnerAppCalendarMajorIcon, "AppCalendarMajorIcon");
export const AppChannelMajorIcon = createOrbitIcon(InnerAppChannelMajorIcon, "AppChannelMajorIcon");
export const AppChannelMinorIcon = createOrbitIcon(InnerAppChannelMinorIcon, "AppChannelMinorIcon");
export const AppChevronUpDownMajorIcon = createOrbitIcon(InnerAppChevronUpDownMajorIcon, "AppChevronUpDownMajorIcon");
export const AppChevronUpDownMinorIcon = createOrbitIcon(InnerAppChevronUpDownMinorIcon, "AppChevronUpDownMinorIcon");
export const AppCloudCopyMajorIcon = createOrbitIcon(InnerAppCloudCopyMajorIcon, "AppCloudCopyMajorIcon");
export const AppCopyToOneDriveMajorIcon = createOrbitIcon(InnerAppCopyToOneDriveMajorIcon, "AppCopyToOneDriveMajorIcon");
export const AppDashboardMajorIcon = createOrbitIcon(InnerAppDashboardMajorIcon, "AppDashboardMajorIcon");
export const AppDotMajorIcon = createOrbitIcon(InnerAppDotMajorIcon, "AppDotMajorIcon");
export const AppDuplicateMajorIcon = createOrbitIcon(InnerAppDuplicateMajorIcon, "AppDuplicateMajorIcon");
export const AppExternalLinkMajorIcon = createOrbitIcon(InnerAppExternalLinkMajorIcon, "AppExternalLinkMajorIcon");
export const AppExternalReviewReviewStartedIcon = createOrbitIcon(InnerAppExternalReviewReviewStartedIcon, "AppExternalReviewReviewStartedIcon");
export const AppFolderMajorIcon = createOrbitIcon(InnerAppFolderMajorIcon, "AppFolderMajorIcon");
export const AppGrabMajorIcon = createOrbitIcon(InnerAppGrabMajorIcon, "AppGrabMajorIcon");
export const AppGuestAllowedMajorIcon = createOrbitIcon(InnerAppGuestAllowedMajorIcon, "AppGuestAllowedMajorIcon");
export const AppGuestNotAllowedMajorIcon = createOrbitIcon(InnerAppGuestNotAllowedMajorIcon, "AppGuestNotAllowedMajorIcon");
export const AppHelpCircleMajorIcon = createOrbitIcon(InnerAppHelpCircleMajorIcon, "AppHelpCircleMajorIcon");
export const AppHomeMajorIcon = createOrbitIcon(InnerAppHomeMajorIcon, "AppHomeMajorIcon");
export const AppIconUserPlusMinorIcon = createOrbitIcon(InnerAppIconUserPlusMinorIcon, "AppIconUserPlusMinorIcon");
export const AppInactiveMajorIcon = createOrbitIcon(InnerAppInactiveMajorIcon, "AppInactiveMajorIcon");
export const AppKeepMajorIcon = createOrbitIcon(InnerAppKeepMajorIcon, "AppKeepMajorIcon");
export const AppKeepMinorIcon = createOrbitIcon(InnerAppKeepMinorIcon, "AppKeepMinorIcon");
export const AppKeyMajorIcon = createOrbitIcon(InnerAppKeyMajorIcon, "AppKeyMajorIcon");
export const AppLinkMajorIcon = createOrbitIcon(InnerAppLinkMajorIcon, "AppLinkMajorIcon");
export const AppLinkRemoveMajorIcon = createOrbitIcon(InnerAppLinkRemoveMajorIcon, "AppLinkRemoveMajorIcon");
export const AppManageColumnsMajorIcon = createOrbitIcon(InnerAppManageColumnsMajorIcon, "AppManageColumnsMajorIcon");
export const AppManageMajorIcon = createOrbitIcon(InnerAppManageMajorIcon, "AppManageMajorIcon");
export const AppMigrationMajorIcon = createOrbitIcon(InnerAppMigrationMajorIcon, "AppMigrationMajorIcon");
export const AppPencilMajorIcon = createOrbitIcon(InnerAppPencilMajorIcon, "AppPencilMajorIcon");
export const AppPlaceholderMajorIcon = createOrbitIcon(InnerAppPlaceholderMajorIcon, "AppPlaceholderMajorIcon");
export const AppPlaceholderMinorIcon = createOrbitIcon(InnerAppPlaceholderMinorIcon, "AppPlaceholderMinorIcon");
export const AppPoliciesMajorIcon = createOrbitIcon(InnerAppPoliciesMajorIcon, "AppPoliciesMajorIcon");
export const AppPrivacyPublicMajorIcon = createOrbitIcon(InnerAppPrivacyPublicMajorIcon, "AppPrivacyPublicMajorIcon");
export const AppProvisioningMajorIcon = createOrbitIcon(InnerAppProvisioningMajorIcon, "AppProvisioningMajorIcon");
export const AppRevertMajorIcon = createOrbitIcon(InnerAppRevertMajorIcon, "AppRevertMajorIcon");
export const AppRobotMajorIcon = createOrbitIcon(InnerAppRobotMajorIcon, "AppRobotMajorIcon");
export const AppRobotMinorIcon = createOrbitIcon(InnerAppRobotMinorIcon, "AppRobotMinorIcon");
export const AppSharingAnyoneMajorIcon = createOrbitIcon(InnerAppSharingAnyoneMajorIcon, "AppSharingAnyoneMajorIcon");
export const AppSharingExistingGuestsMajorIcon = createOrbitIcon(InnerAppSharingExistingGuestsMajorIcon, "AppSharingExistingGuestsMajorIcon");
export const AppSharingNewExistingGuestsMajorIcon = createOrbitIcon(InnerAppSharingNewExistingGuestsMajorIcon, "AppSharingNewExistingGuestsMajorIcon");
export const AppSharingNoExternalSharingIcon = createOrbitIcon(InnerAppSharingNoExternalSharingIcon, "AppSharingNoExternalSharingIcon");
export const AppSigninMajorIcon = createOrbitIcon(InnerAppSigninMajorIcon, "AppSigninMajorIcon");
export const AppTagAddMajorIcon = createOrbitIcon(InnerAppTagAddMajorIcon, "AppTagAddMajorIcon");
export const AppTagAddMinorIcon = createOrbitIcon(InnerAppTagAddMinorIcon, "AppTagAddMinorIcon");
export const AppTagMajorIcon = createOrbitIcon(InnerAppTagMajorIcon, "AppTagMajorIcon");
export const AppTagNoTagMajorIcon = createOrbitIcon(InnerAppTagNoTagMajorIcon, "AppTagNoTagMajorIcon");
export const AppTagNoTagMinorIcon = createOrbitIcon(InnerAppTagNoTagMinorIcon, "AppTagNoTagMinorIcon");
export const AppTagPurposeMajorIcon = createOrbitIcon(InnerAppTagPurposeMajorIcon, "AppTagPurposeMajorIcon");
export const AppTagSensitivityMajorIcon = createOrbitIcon(InnerAppTagSensitivityMajorIcon, "AppTagSensitivityMajorIcon");
export const AppUserMajorIcon = createOrbitIcon(InnerAppUserMajorIcon, "AppUserMajorIcon");
export const AppUserMinorIcon = createOrbitIcon(InnerAppUserMinorIcon, "AppUserMinorIcon");
export const AppUserPlusMajorIcon = createOrbitIcon(InnerAppUserPlusMajorIcon, "AppUserPlusMajorIcon");
export const ArrowMajorIcon = createOrbitIcon(InnerArrowMajorIcon, "ArrowMajorIcon");
export const ArrowMinorIcon = createOrbitIcon(InnerArrowMinorIcon, "ArrowMinorIcon");
export const CalendarMajorIcon = createOrbitIcon(InnerCalendarMajorIcon, "CalendarMajorIcon");
export const CheckMajorIcon = createOrbitIcon(InnerCheckMajorIcon, "CheckMajorIcon");
export const CheckMinorIcon = createOrbitIcon(InnerCheckMinorIcon, "CheckMinorIcon");
export const ChevronMajorIcon = createOrbitIcon(InnerChevronMajorIcon, "ChevronMajorIcon");
export const ChevronMinorIcon = createOrbitIcon(InnerChevronMinorIcon, "ChevronMinorIcon");
export const CrossMajorIcon = createOrbitIcon(InnerCrossMajorIcon, "CrossMajorIcon");
export const CrossMinorIcon = createOrbitIcon(InnerCrossMinorIcon, "CrossMinorIcon");
export const DownloadMajorIcon = createOrbitIcon(InnerDownloadMajorIcon, "DownloadMajorIcon");
export const EmailMajorIcon = createOrbitIcon(InnerEmailMajorIcon, "EmailMajorIcon");
export const EyeMajorIcon = createOrbitIcon(InnerEyeMajorIcon, "EyeMajorIcon");
export const FileCsvMajorIcon = createOrbitIcon(InnerFileCsvMajorIcon, "FileCsvMajorIcon");
export const FileMajorIcon = createOrbitIcon(InnerFileMajorIcon, "FileMajorIcon");
export const FileMusicMajorIcon = createOrbitIcon(InnerFileMusicMajorIcon, "FileMusicMajorIcon");
export const FilePdfMajorIcon = createOrbitIcon(InnerFilePdfMajorIcon, "FilePdfMajorIcon");
export const FileVideoMajorIcon = createOrbitIcon(InnerFileVideoMajorIcon, "FileVideoMajorIcon");
export const FileZipMajorIcon = createOrbitIcon(InnerFileZipMajorIcon, "FileZipMajorIcon");
export const FilterMajorIcon = createOrbitIcon(InnerFilterMajorIcon, "FilterMajorIcon");
export const FolderMajorIcon = createOrbitIcon(InnerFolderMajorIcon, "FolderMajorIcon");
export const GearMajorIcon = createOrbitIcon(InnerGearMajorIcon, "GearMajorIcon");
export const GroupMajorIcon = createOrbitIcon(InnerGroupMajorIcon, "GroupMajorIcon");
export const GuestRemoveMajorIcon = createOrbitIcon(InnerGuestRemoveMajorIcon, "GuestRemoveMajorIcon");
export const HelpMajorIcon = createOrbitIcon(InnerHelpMajorIcon, "HelpMajorIcon");
export const HorizontalDotsMajorIcon = createOrbitIcon(InnerHorizontalDotsMajorIcon, "HorizontalDotsMajorIcon");
export const ImageMajorIcon = createOrbitIcon(InnerImageMajorIcon, "ImageMajorIcon");
export const InfoCircleMajorIcon = createOrbitIcon(InnerInfoCircleMajorIcon, "InfoCircleMajorIcon");
export const InfoCircleMinorIcon = createOrbitIcon(InnerInfoCircleMinorIcon, "InfoCircleMinorIcon");
export const LightbulbMajorIcon = createOrbitIcon(InnerLightbulbMajorIcon, "LightbulbMajorIcon");
export const MagnifierMajorIcon = createOrbitIcon(InnerMagnifierMajorIcon, "MagnifierMajorIcon");
export const NotificationMajorIcon = createOrbitIcon(InnerNotificationMajorIcon, "NotificationMajorIcon");
export const NotificationOffMajorIcon = createOrbitIcon(InnerNotificationOffMajorIcon, "NotificationOffMajorIcon");
export const PencilMajorIcon = createOrbitIcon(InnerPencilMajorIcon, "PencilMajorIcon");
export const PlaceholderMajorIcon = createOrbitIcon(InnerPlaceholderMajorIcon, "PlaceholderMajorIcon");
export const PrivacyPrivateMajorIcon = createOrbitIcon(InnerPrivacyPrivateMajorIcon, "PrivacyPrivateMajorIcon");
export const SignoutMajorIcon = createOrbitIcon(InnerSignoutMajorIcon, "SignoutMajorIcon");
export const SortMajorIcon = createOrbitIcon(InnerSortMajorIcon, "SortMajorIcon");
export const StarFillMajorIcon = createOrbitIcon(InnerStarFillMajorIcon, "StarFillMajorIcon");
export const StarOutlineMajorIcon = createOrbitIcon(InnerStarOutlineMajorIcon, "StarOutlineMajorIcon");
export const TrashMajorIcon = createOrbitIcon(InnerTrashMajorIcon, "TrashMajorIcon");
export const TrashMinorIcon = createOrbitIcon(InnerTrashMinorIcon, "TrashMinorIcon");
export const UserAddMajorIcon = createOrbitIcon(InnerUserAddMajorIcon, "UserAddMajorIcon");
export const UserAddMinorIcon = createOrbitIcon(InnerUserAddMinorIcon, "UserAddMinorIcon");
export const VerticalDotsMajorIcon = createOrbitIcon(InnerVerticalDotsMajorIcon, "VerticalDotsMajorIcon");
export const WarningMajorIcon = createOrbitIcon(InnerWarningMajorIcon, "WarningMajorIcon");
export const WarningMinorIcon = createOrbitIcon(InnerWarningMinorIcon, "WarningMinorIcon");
/* eslint-enable */
