/*
* THIS FILE IS GENERATED. DO NOT EDIT IT.
* To re-generate the icons, run the yarn generate-icons-components command in the components project.
*/

/* eslint-disable */
import { createOrbitIcon } from "../createOrbitIcon";

import { ReactComponent as InnerAddMajorIcon } from "./AddMajorIcon24";
import { ReactComponent as InnerAlertMajorIcon } from "./AlertMajorIcon24";
import { ReactComponent as InnerArrowMajorIcon } from "./ArrowMajorIcon24";
import { ReactComponent as InnerArrowMinorIcon } from "./ArrowMinorIcon24";
import { ReactComponent as InnerBurgerMajorIcon } from "./BurgerMajorIcon24";
import { ReactComponent as InnerCalendarMajorIcon } from "./CalendarMajorIcon24";
import { ReactComponent as InnerCheckMajorIcon } from "./CheckMajorIcon24";
import { ReactComponent as InnerCheckMinorIcon } from "./CheckMinorIcon24";
import { ReactComponent as InnerChevronMajorIcon } from "./ChevronMajorIcon24";
import { ReactComponent as InnerChevronMinorIcon } from "./ChevronMinorIcon24";
import { ReactComponent as InnerChevronUpDownMajorIcon } from "./ChevronUpDownMajorIcon24";
import { ReactComponent as InnerChevronUpDownMinorIcon } from "./ChevronUpDownMinorIcon24";
import { ReactComponent as InnerCrossMajorIcon } from "./CrossMajorIcon24";
import { ReactComponent as InnerCrossMinorIcon } from "./CrossMinorIcon24";
import { ReactComponent as InnerDotMajorIcon } from "./DotMajorIcon24";
import { ReactComponent as InnerDownloadMajorIcon } from "./DownloadMajorIcon24";
import { ReactComponent as InnerDuplicateMajorIcon } from "./DuplicateMajorIcon24";
import { ReactComponent as InnerEmailMajorIcon } from "./EmailMajorIcon24";
import { ReactComponent as InnerExternalLinkMajorIcon } from "./ExternalLinkMajorIcon24";
import { ReactComponent as InnerEyeMajorIcon } from "./EyeMajorIcon24";
import { ReactComponent as InnerFileCsvMajorIcon } from "./FileCsvMajorIcon24";
import { ReactComponent as InnerFileMajorIcon } from "./FileMajorIcon24";
import { ReactComponent as InnerFileMusicMajorIcon } from "./FileMusicMajorIcon24";
import { ReactComponent as InnerFilePdfMajorIcon } from "./FilePdfMajorIcon24";
import { ReactComponent as InnerFileVideoMajorIcon } from "./FileVideoMajorIcon24";
import { ReactComponent as InnerFileZipMajorIcon } from "./FileZipMajorIcon24";
import { ReactComponent as InnerFilterMajorIcon } from "./FilterMajorIcon24";
import { ReactComponent as InnerFolderMajorIcon } from "./FolderMajorIcon24";
import { ReactComponent as InnerGearMajorIcon } from "./GearMajorIcon24";
import { ReactComponent as InnerGrabMajorIcon } from "./GrabMajorIcon24";
import { ReactComponent as InnerGroupMajorIcon } from "./GroupMajorIcon24";
import { ReactComponent as InnerHelpCircleMajorIcon } from "./HelpCircleMajorIcon24";
import { ReactComponent as InnerHelpMajorIcon } from "./HelpMajorIcon24";
import { ReactComponent as InnerHomeMajorIcon } from "./HomeMajorIcon24";
import { ReactComponent as InnerHorizontalDotsMajorIcon } from "./HorizontalDotsMajorIcon24";
import { ReactComponent as InnerImageMajorIcon } from "./ImageMajorIcon24";
import { ReactComponent as InnerInfoCircleMajorIcon } from "./InfoCircleMajorIcon24";
import { ReactComponent as InnerInfoCircleMinorIcon } from "./InfoCircleMinorIcon24";
import { ReactComponent as InnerLightbulbMajorIcon } from "./LightbulbMajorIcon24";
import { ReactComponent as InnerLinkMajorIcon } from "./LinkMajorIcon24";
import { ReactComponent as InnerLinkRemoveMajorIcon } from "./LinkRemoveMajorIcon24";
import { ReactComponent as InnerMagnifierMajorIcon } from "./MagnifierMajorIcon24";
import { ReactComponent as InnerNotificationMajorIcon } from "./NotificationMajorIcon24";
import { ReactComponent as InnerNotificationOffMajorIcon } from "./NotificationOffMajorIcon24";
import { ReactComponent as InnerPadlockLockedMajorIcon } from "./PadlockLockedMajorIcon24";
import { ReactComponent as InnerPadlockUnlockedMajorIcon } from "./PadlockUnlockedMajorIcon24";
import { ReactComponent as InnerPencilMajorIcon } from "./PencilMajorIcon24";
import { ReactComponent as InnerPlaceholderMajorIcon } from "./PlaceholderMajorIcon24";
import { ReactComponent as InnerPlaceholderMinorIcon } from "./PlaceholderMinorIcon24";
import { ReactComponent as InnerRevertMajorIcon } from "./RevertMajorIcon24";
import { ReactComponent as InnerRocketMajorIcon } from "./RocketMajorIcon24";
import { ReactComponent as InnerSigninMajorIcon } from "./SigninMajorIcon24";
import { ReactComponent as InnerSignoutMajorIcon } from "./SignoutMajorIcon24";
import { ReactComponent as InnerSortMajorIcon } from "./SortMajorIcon24";
import { ReactComponent as InnerStarFillMajorIcon } from "./StarFillMajorIcon24";
import { ReactComponent as InnerStarOutlineMajorIcon } from "./StarOutlineMajorIcon24";
import { ReactComponent as InnerTelescopeMajorIcon } from "./TelescopeMajorIcon24";
import { ReactComponent as InnerTrashMajorIcon } from "./TrashMajorIcon24";
import { ReactComponent as InnerTrashMinorIcon } from "./TrashMinorIcon24";
import { ReactComponent as InnerUfoMajorIcon } from "./UfoMajorIcon24";
import { ReactComponent as InnerUserAddMajorIcon } from "./UserAddMajorIcon24";
import { ReactComponent as InnerUserAddMinorIcon } from "./UserAddMinorIcon24";
import { ReactComponent as InnerUserMajorIcon } from "./UserMajorIcon24";
import { ReactComponent as InnerUserMinorIcon } from "./UserMinorIcon24";
import { ReactComponent as InnerVerticalDotsMajorIcon } from "./VerticalDotsMajorIcon24";
import { ReactComponent as InnerWarningMajorIcon } from "./WarningMajorIcon24";
import { ReactComponent as InnerWarningMinorIcon } from "./WarningMinorIcon24";

export const AddMajorIcon = createOrbitIcon(InnerAddMajorIcon, "AddMajorIcon");
export const AlertMajorIcon = createOrbitIcon(InnerAlertMajorIcon, "AlertMajorIcon");
export const ArrowMajorIcon = createOrbitIcon(InnerArrowMajorIcon, "ArrowMajorIcon");
export const ArrowMinorIcon = createOrbitIcon(InnerArrowMinorIcon, "ArrowMinorIcon");
export const BurgerMajorIcon = createOrbitIcon(InnerBurgerMajorIcon, "BurgerMajorIcon");
export const CalendarMajorIcon = createOrbitIcon(InnerCalendarMajorIcon, "CalendarMajorIcon");
export const CheckMajorIcon = createOrbitIcon(InnerCheckMajorIcon, "CheckMajorIcon");
export const CheckMinorIcon = createOrbitIcon(InnerCheckMinorIcon, "CheckMinorIcon");
export const ChevronMajorIcon = createOrbitIcon(InnerChevronMajorIcon, "ChevronMajorIcon");
export const ChevronMinorIcon = createOrbitIcon(InnerChevronMinorIcon, "ChevronMinorIcon");
export const ChevronUpDownMajorIcon = createOrbitIcon(InnerChevronUpDownMajorIcon, "ChevronUpDownMajorIcon");
export const ChevronUpDownMinorIcon = createOrbitIcon(InnerChevronUpDownMinorIcon, "ChevronUpDownMinorIcon");
export const CrossMajorIcon = createOrbitIcon(InnerCrossMajorIcon, "CrossMajorIcon");
export const CrossMinorIcon = createOrbitIcon(InnerCrossMinorIcon, "CrossMinorIcon");
export const DotMajorIcon = createOrbitIcon(InnerDotMajorIcon, "DotMajorIcon");
export const DownloadMajorIcon = createOrbitIcon(InnerDownloadMajorIcon, "DownloadMajorIcon");
export const DuplicateMajorIcon = createOrbitIcon(InnerDuplicateMajorIcon, "DuplicateMajorIcon");
export const EmailMajorIcon = createOrbitIcon(InnerEmailMajorIcon, "EmailMajorIcon");
export const ExternalLinkMajorIcon = createOrbitIcon(InnerExternalLinkMajorIcon, "ExternalLinkMajorIcon");
export const EyeMajorIcon = createOrbitIcon(InnerEyeMajorIcon, "EyeMajorIcon");
export const FileCsvMajorIcon = createOrbitIcon(InnerFileCsvMajorIcon, "FileCsvMajorIcon");
export const FileMajorIcon = createOrbitIcon(InnerFileMajorIcon, "FileMajorIcon");
export const FileMusicMajorIcon = createOrbitIcon(InnerFileMusicMajorIcon, "FileMusicMajorIcon");
export const FilePdfMajorIcon = createOrbitIcon(InnerFilePdfMajorIcon, "FilePdfMajorIcon");
export const FileVideoMajorIcon = createOrbitIcon(InnerFileVideoMajorIcon, "FileVideoMajorIcon");
export const FileZipMajorIcon = createOrbitIcon(InnerFileZipMajorIcon, "FileZipMajorIcon");
export const FilterMajorIcon = createOrbitIcon(InnerFilterMajorIcon, "FilterMajorIcon");
export const FolderMajorIcon = createOrbitIcon(InnerFolderMajorIcon, "FolderMajorIcon");
export const GearMajorIcon = createOrbitIcon(InnerGearMajorIcon, "GearMajorIcon");
export const GrabMajorIcon = createOrbitIcon(InnerGrabMajorIcon, "GrabMajorIcon");
export const GroupMajorIcon = createOrbitIcon(InnerGroupMajorIcon, "GroupMajorIcon");
export const HelpCircleMajorIcon = createOrbitIcon(InnerHelpCircleMajorIcon, "HelpCircleMajorIcon");
export const HelpMajorIcon = createOrbitIcon(InnerHelpMajorIcon, "HelpMajorIcon");
export const HomeMajorIcon = createOrbitIcon(InnerHomeMajorIcon, "HomeMajorIcon");
export const HorizontalDotsMajorIcon = createOrbitIcon(InnerHorizontalDotsMajorIcon, "HorizontalDotsMajorIcon");
export const ImageMajorIcon = createOrbitIcon(InnerImageMajorIcon, "ImageMajorIcon");
export const InfoCircleMajorIcon = createOrbitIcon(InnerInfoCircleMajorIcon, "InfoCircleMajorIcon");
export const InfoCircleMinorIcon = createOrbitIcon(InnerInfoCircleMinorIcon, "InfoCircleMinorIcon");
export const LightbulbMajorIcon = createOrbitIcon(InnerLightbulbMajorIcon, "LightbulbMajorIcon");
export const LinkMajorIcon = createOrbitIcon(InnerLinkMajorIcon, "LinkMajorIcon");
export const LinkRemoveMajorIcon = createOrbitIcon(InnerLinkRemoveMajorIcon, "LinkRemoveMajorIcon");
export const MagnifierMajorIcon = createOrbitIcon(InnerMagnifierMajorIcon, "MagnifierMajorIcon");
export const NotificationMajorIcon = createOrbitIcon(InnerNotificationMajorIcon, "NotificationMajorIcon");
export const NotificationOffMajorIcon = createOrbitIcon(InnerNotificationOffMajorIcon, "NotificationOffMajorIcon");
export const PadlockLockedMajorIcon = createOrbitIcon(InnerPadlockLockedMajorIcon, "PadlockLockedMajorIcon");
export const PadlockUnlockedMajorIcon = createOrbitIcon(InnerPadlockUnlockedMajorIcon, "PadlockUnlockedMajorIcon");
export const PencilMajorIcon = createOrbitIcon(InnerPencilMajorIcon, "PencilMajorIcon");
export const PlaceholderMajorIcon = createOrbitIcon(InnerPlaceholderMajorIcon, "PlaceholderMajorIcon");
export const PlaceholderMinorIcon = createOrbitIcon(InnerPlaceholderMinorIcon, "PlaceholderMinorIcon");
export const RevertMajorIcon = createOrbitIcon(InnerRevertMajorIcon, "RevertMajorIcon");
export const RocketMajorIcon = createOrbitIcon(InnerRocketMajorIcon, "RocketMajorIcon");
export const SigninMajorIcon = createOrbitIcon(InnerSigninMajorIcon, "SigninMajorIcon");
export const SignoutMajorIcon = createOrbitIcon(InnerSignoutMajorIcon, "SignoutMajorIcon");
export const SortMajorIcon = createOrbitIcon(InnerSortMajorIcon, "SortMajorIcon");
export const StarFillMajorIcon = createOrbitIcon(InnerStarFillMajorIcon, "StarFillMajorIcon");
export const StarOutlineMajorIcon = createOrbitIcon(InnerStarOutlineMajorIcon, "StarOutlineMajorIcon");
export const TelescopeMajorIcon = createOrbitIcon(InnerTelescopeMajorIcon, "TelescopeMajorIcon");
export const TrashMajorIcon = createOrbitIcon(InnerTrashMajorIcon, "TrashMajorIcon");
export const TrashMinorIcon = createOrbitIcon(InnerTrashMinorIcon, "TrashMinorIcon");
export const UfoMajorIcon = createOrbitIcon(InnerUfoMajorIcon, "UfoMajorIcon");
export const UserAddMajorIcon = createOrbitIcon(InnerUserAddMajorIcon, "UserAddMajorIcon");
export const UserAddMinorIcon = createOrbitIcon(InnerUserAddMinorIcon, "UserAddMinorIcon");
export const UserMajorIcon = createOrbitIcon(InnerUserMajorIcon, "UserMajorIcon");
export const UserMinorIcon = createOrbitIcon(InnerUserMinorIcon, "UserMinorIcon");
export const VerticalDotsMajorIcon = createOrbitIcon(InnerVerticalDotsMajorIcon, "VerticalDotsMajorIcon");
export const WarningMajorIcon = createOrbitIcon(InnerWarningMajorIcon, "WarningMajorIcon");
export const WarningMinorIcon = createOrbitIcon(InnerWarningMinorIcon, "WarningMinorIcon");
/* eslint-enable */
